### ISSUE TITLE
 Indicate Matlab Version and OS tested

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [gibbonCode/GIBBON#10]
This issue replaces [#507](https://github.com/openjournals/joss-reviews/issues/507) raised by @siboles  

> I've installed in R2015a Matlab on Arch Linux. It seems your Linux testing is on an Ubuntu machine, which is probably the best choice for the widest audience. Most things went smoothly, although the help did not integrate for me. I'm not sure if it is my Matlab version, how I installed on Arch, or something else. My Matlab skills are not the greatest.
I would however, indicate somewhere in the paper.md or the README what Matlab Version you've tested on, or if a minimum version is known, and also the Linux OS, and the minimum Windows version.

**Comment by Kevin-Mattheus-Moerman** [comment]
@siboles thanks reviewing GIBBON and for raising this issue. 

I've started to address this in https://github.com/gibbonCode/GIBBON#Test I'll expand on this and will add more detail shortly. I'll also list more information on the versions for the other third party software (TetGen/FEBio). 

About your Arch Linux issue. 
1. Does the installation and help integration process proceed without errors? 
2. Did you restart MATLAB as suggested? 
3. When you view the browser style documentation in MATLAB does it have "Supplimental software" listed as below? 
![screenshot from 2017-12-14 09-55-58](https://user-images.githubusercontent.com/8392709/34011702-08c37be8-e0b5-11e7-8b74-30ab1621e2d9.png)

I believe the integrated help started with MATLAB 2013 so it should work with MATLAB 2015. If this issue persists I'll try to find a colleague with Arch Linux to explore what is going on. The integration will render the help in a "pretty" way. For now you can also see the documentation rendered here: https://www.gibboncode.org/Documentation/. The easiest thing to do also is to type `HELP_...` or `DEMO_...` in the command window, and to use Tab to see suggested files that start with that name. FEBio examples are named `DEMO_FEBio...`.

**Comment by siboles** [comment]
@Kevin-Mattheus-Moerman It is unnecessary to trouble yourself with support for Arch Linux. The point was more to indicate on what Linux flavour development and testing was done. So far using HELP_ and DEMO_ from the command line has been working smoothly. Beautiful figure generation and integration with FEBio!

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks. On visualization, note that some examples like `DEMO_FEBio_bar_twist` and 'DEMO_FEBio_trabeculae_compression' also have the new `anim8` based animation implemented to view the results. For these the last figure contains a play bottom in the top left to animate the simulated data.

**Comment by siboles** [comment]
Since everything for the installation working except for the integrated help, and I am on a non-mainstream setup, I think it is fair to close this issue.
