### ISSUE TITLE
Request for basic introductory videos for someone starting out with GIBBON.

### ISSUE THREAD

**Issue by DebjitHore** [gibbonCode/GIBBON#100]
Hi,

As we had discussed, I am posting this issue making a formal request so you can explore the option of launching a few introductory videos which will be immensely helpful for anyone looking to start out with the GIBBON toolbox. Thanks a ton, in advance.

**Comment by Kevin-Mattheus-Moerman** [comment]
I have started posting videos here: 
https://www.youtube.com/channel/UCAZpAC3ETIT8Kcygb-R-AEA

Please let me know if you need a video on a particular topic. 

I'll close this issue for now but let me know if you have any more questions/suggestions. Thanks!

**Comment by DebjitHore** [comment]
Thanks a lot, Kevin. This will be really helpful.
Thank you for looking out for your userbase.
