### ISSUE TITLE
Facing error in meshing

### ISSUE THREAD

**Issue by rehan-bhatia** [gibbonCode/GIBBON#101]
Hi!
I was trying to mesh a geometry, but it returns the same error every time. I have meshed more complex geometries, however only this file is giving me error.
As I mentioned on Gitter, the error shows that the difficulty is only in visualisation, however, the meshOutput parameters are all empty arrays, which suggests that it is actually an error in meshing.
I am new to Gibboncode, so it would be great if you could help in resolving this problem. I am attaching the .m file and the STL as well.
Thanks!

[meshing_error.zip](https://github.com/gibbonCode/GIBBON/files/6708559/meshing_error.zip)

**Comment by Kevin-Mattheus-Moerman** [comment]
@rehan-bhatia did you attach the STL file? I cannot see it in the zip file

**Comment by Kevin-Mattheus-Moerman** [comment]
I'll close this issue now as this issue might have gone stale. Let me know if you need more help.
