### ISSUE TITLE
cylinder patchThick

### ISSUE THREAD

**Issue by jpv20** [gibbonCode/GIBBON#105]
Kevin,

is there code in Gibbon to filter (delineate) the 4 different boundary faces from a set of all boundary faces in a cylinder mesh?  (fyi - i am using patchThick to generate the cylinder mesh....

thanks
jonathan

**Comment by Kevin-Mattheus-Moerman** [comment]
1. If you are using hexahedral elements, here is the simplest approach for this case. When you are converting from elements to faces you can also request the "face type" (e.g. top, bottom, left, right, front, back). Note the additional output requested `CF`:

```matlab
%Use element2patch to get patch data 
[F,~,CF]=element2patch(E); %Get faces and face type label (top, left, bottom, etc)
```
For hexahedra there a 6 types (top, bottom, left, right, front, back). Subsequently you can use the following to pick out only your boundary faces and to also only pick out the boundary face type labels. 

```matlab
indBoundaryFaces=tesBoundary(F,V); %Indices for boundary faces
Fb=F(indBoundaryFaces,:); %The boundary face set
CFb=CF(indBoundaryFaces,:); %The face types for the boundary faces
```
The following should help you visualize the face labels, this process/method is fully repeatable and labels depend only on the element connectivity of the hexahedral elements: 
```matlab
cFigure; hold on;
gpatch(Fb,V,CFb,'k',0.5);
axisGeom;
camlight headlight;
colormap gjet; icolorbar;
drawnow;
```

2. Another option is to harness the additional outputs for patchThick Note that for `patchThick` there are two additional outputs `F1` and `F2`
```matlab
[E,V,F1,F2]=patchThick(Fs,Vs,1,layerThickness,numSteps);
```
These are the start and end faces. So, if you thicken a cylinder in the outward direction then `F1` is the inner surface and `F2` the outer surface. You could then get the top and bottom surface using other methods, e.g. face normal directions if you like (happy to explain this more if needed). 

3. A more general approach that you should check out for the future (slower though but works for any geometry) which works for any geometry (not just regular geometry or geometry from `patchThick`) is:  `patchFeatureDetect` (see [`HELP_patchFeatureDetect`](https://www.gibboncode.org/html/HELP_patchFeatureDetect.html)), which automatically labels surface regions based on angles. The output `CFb` below is similar to CFb above. This labeling can be slow as regions are iteratively grown on the input geometry based on the angular threshold. Although the order of the labeling is repeatable is does depend on the mesh configuration and element order. 

```matlab
angleThreshold=30*(pi/180); %Angular threshold to consider surface segments as continuous
CFb=patchFeatureDetect(Fb,V,angleThreshold); %Get labelling
```

Does this answer your question?

**Comment by jpv20** [comment]
Kevin - yes that helps a great deal....patchFeatureDetect is exactly what i needed!  i figured you had done this but didn't know where to find it!  thanks again!

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. I'll close this for now but let me know if you need anything else and we'll reopen the issue.
