### ISSUE TITLE
Error in febioStruct2xml>febioStruct2xmlStep febio2.5

### ISSUE THREAD

**Issue by jszyszko** [gibbonCode/GIBBON#106]
Hi everyone,
I have faced some issues while saving the febio file. I use the febio-2.6.4 version and I have succesfully run some scripts for febio_spec version="2.0". However, while trying to run the DEMO script for version 2.5 (DEMO_febio_0052_breast_gap_close_01.m) I have the following errors:

_Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in cell2txtfile (line 63)
        fprintf(fid,'%s\r\n', T{:});

Error in febioStruct2xml>textModeElementAttributeParse (line 321)
cell2txtfile(fileName,totalTextCell,0,0); %Export to text file

Error in febioStruct2xml>febioStruct2xmlStep (line 178)
                            [domNode,rootNode]=textModeElementAttributeParse(domNode,rootNode,currentFieldName,attributeStruct,arrayDataSet,numArray,fieldNameSetSub,fileName,arrayParseMethod);

Error in febioStruct2xml>recursiveElementParse (line 228)
        [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,parseStructSub,optionStruct,fileName); %Add
        whatever is nested in here

Error in febioStruct2xml>febioStruct2xmlStep (line 210)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml>recursiveElementParse (line 223)
    [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,currentFieldValue,optionStruct,fileName); %Add
    whatever is nested in here

Error in febioStruct2xml>febioStruct2xmlStep (line 210)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml (line 78)
[domNode]=febioStruct2xmlStep(domNode,rootNode,parseStruct,optionStruct,fileName);

Error in DEMO_febio_0052_breast_gap_close_01 (line 372)
febioStruct2xml(febio_spec,febioFebFileName); %Exporting to file and domNode_

Could you please advise how to proceed? Thank you in advance.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jszyszko thanks for posting this. I checked the demo just now and with the latest FEBio version it still works. 

FEBio implemented quite a number of changes over the last ~1.5 years that required me to alter the codes a lot. Could you try the latest FEBio version? Unfortunately I do not have the bandwidth to keep my codes working for all past versions of FEBio. Also they really did make more changes than usual with the latest febio_spec changes which have been a challenge. Another option is to try to use a much older version of GIBBON. 

Let me know how you get on. I'll close this issue for now but let me know if you need more help and I'll reopen it.

**Comment by Fireedman** [comment]
that error with fprint is usually attached to error with febio files generation. TRy to verify the way that you are making the files in matlab
