### ISSUE TITLE
runTetGen with -i option (Add Points on Internal Surface)

### ISSUE THREAD

**Issue by LawSmith408** [gibbonCode/GIBBON#109]
I am trying to generate a tet mesh inside the green cube, which contains the blue points. It seems like there is a tetGen option for specifying additional points interior to the mesh volume that should be included in the mesh list. 
https://wias-berlin.de/software/tetgen/switches.i.html

Is there a way to ask Gibbon's runTetGen to do this?

![image](https://user-images.githubusercontent.com/32077819/135296802-4d7e7832-f54d-4dc2-8746-b03bfa7ab644.png)

**Comment by LawSmith408** [comment]
Hi Dr. Moerman - thank you for the feedback! I have not checked back in quite a while, so I apologize for the delay here.

I have never made a pull request, I will look up how to do this tomorrow and then contribute a minimum working example.

I am interested in formally contributing to GibbonCode - it has been a huge help to me over the last year. Right now I am working on a RVE homogenization demo using FEBio and GibbonCode. If I get that working, I will contribute it as well.

**Comment by Kevin-Mattheus-Moerman** [comment]
@LawSmith408 any updates on this. If you have code to contribute it would be great.
