### ISSUE TITLE
Windows - Record of all DEMO_ runs

### ISSUE THREAD

**Issue by siboles** [gibbonCode/GIBBON#12]
@Kevin-Mattheus-Moerman openjournals/joss-reviews#506

My colleague, @azimj, ran all the demos on a Windows machine. He has logged the command window output in the attached file  - [run_tests_201712191554.txt](https://github.com/gibbonCode/GIBBON/files/1573648/run_tests_201712191554.txt). 

Seems all passed but two.
DEMO_FEBio_beam_L_force.m (this passed for me)

and

DEMO_FEBio_skin_sphere_indentation_tet4_vs_tet10.m (FEBio Error Termination)

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for catching these. I think these are simply FEBio issues. The first model is force controlled and the second involves contact and non-linear elements. Both could benefit from altered FEA control parameters and it may be that they solve in one FEBio version and not in another. For instance I think using full-Newton iterations will help with these. To use that set max_ups to 0. See below. I've been running these on the latest FEBio version (2.6.4). 

For both demos I've now added a set of FEA control parameters at the top so the user can alter them more easily. There may be other e.g. contact related demos that could be "fragile" in this sense so I'll likely update those with similar settings if this seems to solve it. 

`%FEA control settings`
`nSteps=20; %Number of time steps desired`
`max_refs=25; %Max reforms`
`max_ups=0; %Set to zero to use full-Newton iterations`
`opt_iter=10; %Optimum number of iterations`
`max_retries=5; %Maximum number of retires`
`dtmin=(1/nSteps)/100; %Minimum time step size`
`dtmax=1/nSteps; %Maximum time step size`

**Comment by siboles** [comment]
I would recommend running all the demos in full-Newton. The consistency would be worth the trade-off in efficiency. For contact, I always found facet-to-facet sliding, two pass, using penalty rather than Langrange multipliers to be more robust. Of course the penalty method will exhibit some penetration depending on how high relative to the material properties one sets the value. Likewise, for the biphasic contact sliding2 constraint. I think it is fair to close this issue now though.

**Comment by Kevin-Mattheus-Moerman** [comment]
All demos now run in full-Newton mode
