### ISSUE TITLE
how to uninstall GIBBON?

### ISSUE THREAD

**Issue by AlDanial** [gibbonCode/GIBBON#130]
Is there a way to undo the actions of ``installGibbon.m`` ?  I installed GIBBON into a temporary directory to run some tests and later deleted the directory.  Now my matlab sessions begin with a stream of errors complaining about the absence of the deleted directories.  It would be great to see an addition to https://github.com/gibbonCode/GIBBON#Installation that explains how to uninstall the software.

**Comment by Kevin-Mattheus-Moerman** [comment]
Good point about adding "uninstall instructions". We will work on that. 

In the mean time you can go to the `Home` tab in MATLAB and then go to `Set Path`. There you can see all paths that are "visible" to MATLAB for all your codes. You can also see there is a set of paths for your GIBBON folder. These were added during installation (and relate to the red messages you are seeing on start up once these locations no longer exist). You can select all paths there for GIBBON (hold down the SHIFT key and click on the first and last to select the whole set) and then click `Remove`. Next click `Save`, to save the new path definitions. This should resolve your issue. The below GIF animation shows this process too. 

![Peek 2022-01-06 11-02](https://user-images.githubusercontent.com/8392709/148373159-a92745d6-0286-4abf-99e8-852a5871202a.gif)

Let me know if this helped or if you have any other questions.

**Comment by Kevin-Mattheus-Moerman** [comment]
For the future, what is needed is a script called `uninstallGibbon`. This should purge the path definitions mentioned :point_up: and also remove the integrated help definitions.

**Comment by AlDanial** [comment]
Excellent instructions on cleaning up the path, thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@AlDanial I've added an `uninstallGibbon` function just now. I'll go ahead and close this issue now but let me know if you have any other questions. l
