### ISSUE TITLE
Fix remeshTriSurfDistMap to work on non MS Windows systems

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [gibbonCode/GIBBON#14]
`remeshTriSurfDistMap` (see also `DEMO_geodesic_remeshing`) does not run in Ubuntu. Currently the error says:
`Error using perform_fast_marching_mesh (line 66)
You have to run compiler_mex before.`  
However I've not been able to compile it on Ubuntu.

**Comment by siboles** [comment]
I had the same issue on Arch Linux. Matlab lists gcc 4.9 as a compatible compiler, so perhaps this is the issue? It seems Ubuntu is using gcc 5.

**Comment by Kevin-Mattheus-Moerman** [comment]
I no revert to an experimental MATLAB code (that is slower but seems to do the job) if this issue occurs. Users are warned about this and if they want can work on the proper mex compilation to get that to work.
