### ISSUE TITLE
Loading tempModel.feb from DEMO_febio_0050_foot_insole_01

### ISSUE THREAD

**Issue by wyssch** [gibbonCode/GIBBON#141]
Hi
After installing GIBBON and running "DEMO_febio_0050_foot_insole_01" successfully in MATLAB I tried to load the "tempModel.feb" in FEBioStudio. Unfortunatel I get an error message >> see attachement. I could'nt find an error in the xml file. Do you have an idea what's going wrong ??

I use Matlab Version 2022, windows 10, FebioStudio1.8, FEBio 3.0 and the newest version of GIBBON.
Many thanks for an answer.
Christian

![Error](https://user-images.githubusercontent.com/104782392/183063685-309c6792-18b0-42cf-a31f-4ef1e26f18ca.PNG)

**Comment by Kevin-Mattheus-Moerman** [comment]
@wyssch thanks for posting this. I can reproduce this issue on Ubuntu Linux as well. Not sure yet what is going on here. I'll check with @SteveMaas1978 from FEBio.

**Comment by wyssch** [comment]
Thanks for your quick reply. I will curious await the answer.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wyssch your answer came early @SteveMaas1978 said

> FEBio Studio 1 does not have much support for maps. This is something that will be addressed in FEBio Studio 2. 

So GIBBON and FEBio are doing their thing properly here but FEBioStudio is currently lacking support for "maps" which is probably anything that is mapped via the `MeshData` and `ElementData` functionality. 

I hope this helps. Were you importing the model in FEBioStudio for any particular reason?

**Comment by wyssch** [comment]
Thank you, that helps me a lot.
I wanted to change some features in FebioStudio because I'm more familiar with FebioStudio than Febio. That's the only reason. But I can do it that way too. I was just wondering why this doesn't work in FebioStudio. Thank you for your efforts. Sorry if I disturbed you.

**Comment by Kevin-Mattheus-Moerman** [comment]
@wyssch okay. I'll close this issue now as the solution requires changes to FEBioStudio. But do let me know if you have any questions.
