### ISSUE TITLE
git clone https://github.com/DevProxTEAM/DevProx.git && cd DevProx;chmod +x DevProx.sh;./DevProx.sh install

### ISSUE THREAD

**Issue by salik013** [gibbonCode/GIBBON#143]
git clone https://github.com/DevProxTEAM/DevProx.git && cd DevProx;chmod +x DevProx.sh;./DevProx.sh install

**Comment by salik013** [comment]
git clone https://github.com/DevProxTEAM/DevProx.git && cd DevProx;chmod +x DevProx.sh;./DevProx.sh install

**Comment by salik013** [comment]
git clone https://github.com/DevProxTEAM/DevProx.git && cd DevProx;chmod +x DevProx.sh;./DevProx.sh install

**Comment by Kevin-Mattheus-Moerman** [comment]
This looks like spam. Further attempts without clarification will result in the blocking/reporting of this user.
