### ISSUE TITLE
TetGen Test Fails

### ISSUE THREAD

**Issue by jlsimms** [gibbonCode/GIBBON#149]
Hello all,

I'm trying to install GIBBON for a user, and the TetGen test is failing. We're in a Rocky Linux 8 environment, and the error seems related to glibc (see image). As I'm unfamiliar with GIBBON, any advice would be welcome. Reading the docs, it does appear that most testing is on Ubuntu systems, so are RH/CentOS/Rocky/etc. systems known not to work?

Thanks,
Jason
![gibbon-error](https://user-images.githubusercontent.com/5519062/194898931-8e3eff8c-d9df-4e75-b25b-9af0a94a60bd.png)

**Comment by jlsimms** [comment]
Well, it seems that Rocky 8 supports glibc 2.28, and this requires 2.29. I'm unsure that it is wise to attempt an update of glibc just for this one app, but it strikes me as really unfortunate that GIBBON cannot apparently be run on Rocky 8, given that Rocky 9 was just released. It's not as if Rocky 8 is "old" by any definition.

Jason

**Comment by Kevin-Mattheus-Moerman** [comment]
Looks like this user had the same problem: https://github.com/gibbonCode/GIBBON/issues/144

**Comment by Kevin-Mattheus-Moerman** [comment]
More here on GeoGram: https://github.com/gibbonCode/GIBBON/issues/81

**Comment by jlsimms** [comment]
Thanks for the follow up, @Kevin-Mattheus-Moerman. Yeah, as I noted that problem is that Rocky 8 provides version 2.28 by default. And in fact, when you look at [this list of glibc versions by distro](https://repology.org/project/glibc/versions), many are not using >=2.29, so I am glad it's not that Rocky is well behind.

And, thank you for linking to issue #144. It is the same and explains the option to compile well. As it happens, the user in question doesn't actually need either of those tools in his workflow, so I'm lucky. I still might compile it anyway, just to have a complete, working installation.

Warmest regards,
Jason

**Comment by Kevin-Mattheus-Moerman** [comment]
@jlsimms sounds good. I'll close this for now but will reopen on your request if you need more help.
