### ISSUE TITLE
From 3D tetra mesh and data format To gridmesh format

### ISSUE THREAD

**Issue by tmedani** [gibbonCode/GIBBON#151]
Hi @Kevin-Mattheus-Moerman, 

I found your function https://www.mathworks.com/matlabcentral/fileexchange/28327-mesh2tri 
and its a nice funcion, thanks for sharing.

I'm wondering if its possible to do the inverse, i.e, I have a set of tetrahedral mesh [list of nodes and nodal value (x, y, z, V) and elements (n1 n2 n3 n4)], and I would like to convert this data into the Matlab gridmesh format. 

Is there any function on Gibbon toolbox that can do it, or do you have any tip or recommendations to do it?

Thank you in advance :)

Best

**Comment by Kevin-Mattheus-Moerman** [comment]
@tmedani there is no easy way to revert to the grid format. If the underlying mesh is structured you could do something similar (convert to a quadrilateral mesh) with the `tri2quadGroupSplit` function, see this demo: https://www.gibboncode.org/html/HELP_tri2quadGroupSplit.html. 

I'll close this for now but let me know if you need more help/
