### ISSUE TITLE
Holzapfel Gasser Ogden (HGO)

### ISSUE THREAD

**Issue by jpv20** [gibbonCode/GIBBON#159]
heh Kevin,

do you happen to have a gibbon based minimal working example (MWE) for using and HGO model in febio?  parsing out your Matlab material struct format / syntax is giving me challenges in this regard.  it would be great if this MWE clearly showed how to implement material orientations.

let me know either way!
j

ps.  here are some excerpts from a working febio file i have that may help with the febio HGO model:

**Comment by jpv20** [comment]
![Screen Shot 2023-03-23 at 2 54 33 PM](https://user-images.githubusercontent.com/37195559/227319322-e21c3f32-0667-4077-a268-a8eeebf85dac.png)

**Comment by jpv20** [comment]
![Screen Shot 2023-03-23 at 2 54 23 PM](https://user-images.githubusercontent.com/37195559/227319358-ec06ed37-01a1-4b7e-a224-248a1bfcbc03.png)

**Comment by Kevin-Mattheus-Moerman** [comment]
Can you check if this works: 
```matlab
materialName1='Material1';
febio_spec.Material.material{1}.ATTR.name=materialName1;
febio_spec.Material.material{1}.ATTR.type='Holzapfel-Gasser-Ogden';
febio_spec.Material.material{1}.ATTR.id=1;
febio_spec.Material.material{1}.c=7.64;
febio_spec.Material.material{1}.k1=996.6;
febio_spec.Material.material{1}.k2=524.6;
febio_spec.Material.material{1}.gamma=49.98;
febio_spec.Material.material{1}.kappa=0.226;
febio_spec.Material.material{1}.k=1e5;
```

Note this model can act funny as also shown here: https://doi.org/10.1016/j.jmbbm.2014.06.016
And in this quick uni-axial loading check: 
![HGO_uncoupled](https://user-images.githubusercontent.com/8392709/229079759-0b91edbe-e3c1-4a15-9a10-5bb75ae84bac.gif)

The coupled one is safer in that respect: 
```matlab
materialName1='Material1';
febio_spec.Material.material{1}.ATTR.name=materialName1;
febio_spec.Material.material{1}.ATTR.type='HGO unconstrained';
febio_spec.Material.material{1}.ATTR.id=1;
febio_spec.Material.material{1}.c=7.64;
febio_spec.Material.material{1}.k1=996.6;
febio_spec.Material.material{1}.k2=524.6;
febio_spec.Material.material{1}.gamma=49.98;
febio_spec.Material.material{1}.kappa=0.226;
febio_spec.Material.material{1}.k=7.64e3;
```
Which behaves properly: 

![HGO_coupled](https://user-images.githubusercontent.com/8392709/229079840-ebe6760d-6c28-4bfa-bb91-a8dc3d4a1939.gif)

**Comment by Kevin-Mattheus-Moerman** [comment]
I added a demo (number 0083) to the [`febio4`](https://github.com/gibbonCode/GIBBON/tree/febio4) branch now. This branch will be merged with the `master` branch shortly.

**Comment by jpv20** [comment]
thanks Kevin!  i updated to febio4 and i can drag/drop/run the created .feb file in FEBioStudio.  however my matlab function is stalling....its seems like there is an issue with matlab finding the correct filepaths etc. any thoughts on how to get this going?  

just as important - where in the above MWE are you assigning local element material orientations? if they are there let me know - i didn't see them.  if not - would you mind updating the MWE?  (it might be cool if the matlab plot of febio results also indicated the orientation via a quiver or similar.... thanks again!

**Comment by Kevin-Mattheus-Moerman** [comment]
@jpv20 I think we can close this now, we had a meeting on this, and also the updated demos `DEMO_febio_00014_cube_varying_material`, `DEMO_febio_0015_cube_fibers_transiso`, and the new `DEMO_febio_0083_cube_uniaxial_HGO` illustrate all functionality required to do what you want.
