### ISSUE TITLE
`lib/PolyRevolve.m` and `lib/polyrevolve.m` causes problems on macOS

### ISSUE THREAD

**Issue by wspr** [gibbonCode/GIBBON#16]
macOS doesn't distinguish between two files with the same spelling but different capitalisation. This breaks use of Git with the repository, and I suspect Matlab would have troubles down the line with this too.

Is it possible to disambiguate the filenames?

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for spotting this! `polyRevolve` was meant to replace `polyrevolve`. In 1a72179 I have now deleted the latter so the issue is resolved.
