### ISSUE TITLE
Error in febioStruct2xml

### ISSUE THREAD

**Issue by motazalqaoud** [gibbonCode/GIBBON#160]
Hello everyone,

I have some issues while using turning my code in MATLAB. It said that old febio_spec. febio_spec 2.5 is detected, and I should upgrade it to febio_spec 3.0, even though I have the latest version of febio4. Also,  I have the following errors:

Warning: Old febio_spec detected. febio_spec 2.5 is depricated. Please upgrade to febio_spec 3.0 
> In febioStruct2xml (line 81)
Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in cell2txtfile (line 68)
        fprintf(fid,'%s\r\n', T{:});

Error in febioStruct2xml>textModeElementAttributeParse (line 351)
cell2txtfile(fileName,totalTextCell,0,0); %Export to text file

Error in febioStruct2xml>febioStruct2xmlStep (line 208)
                            [domNode,rootNode]=textModeElementAttributeParse(domNode,rootNode,currentFieldName,attributeStruct,arrayDataSet,numArray,fieldNameSetSub,fileName,arrayParseMethod);

Error in febioStruct2xml>recursiveElementParse (line 258)
        [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,parseStructSub,optionStruct,fileName); %Add whatever is nested in here

Error in febioStruct2xml>febioStruct2xmlStep (line 240)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml>recursiveElementParse (line 253)
    [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,currentFieldValue,optionStruct,fileName); %Add whatever is nested in here

Error in febioStruct2xml>febioStruct2xmlStep (line 240)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml (line 103)
[domNode]=febioStruct2xmlStep(domNode,rootNode,parseStruct,optionStruct,fileName);

Thank you,
Motaz

**Comment by motazalqaoud** [comment]
@Kevin-Mattheus-Moerman can you please help me with this?

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @motazalqaoud thanks for posting this. The answer to your issues will be the latest GIBBON updates for FEBio 4 which are currently being finalised here: 
https://github.com/gibbonCode/GIBBON/tree/febio4
We are in the process of adding lots more demos there but demo 1, 2, 3, 6 and 7 have already been updated. We will have many more next week so if you wait we'll have the full set of updates also in the master branch but if you are in a hurry I would grab the febio4 branch code and check out those demos for how to update/fix your code. 

More details: 
Note that FEBio version labels are seperate form the `febio_spec` version labels. `febio_spec` refers to the way the input files are created. `febio_spec 2.5` was used by FEBio 2 and 3 for a bit, then they moved to `febio_spec 3.0`, and now for FEBio4 it is `febio_spec 4.0`. The old code basically check if it is `febio_spec 3.0` (the most recent at the time) and says that your FEBio version is too old if it doesn't match. I suppose that is wrong as the code should say that your FEBio version is too new :) 
Anyway, the demos I refer to above have been made ready for FEBio 4 and `febio_spec 4.0`. More changes are rapidly on their way and we hope to be fully transitioned within about 2 weeks. 

I hope this helps.

**Comment by motazalqaoud** [comment]
Okay, that's clear. Thanks for your kind help.

Best,
Motaz
