### ISSUE TITLE
Rename sliceViewer

### ISSUE THREAD

**Issue by cberggren** [gibbonCode/GIBBON#168]
The GIBBON _sliceViewer_ function competes with the Matlab version in the Image Processing Toolbox that is also named _sliceViewer_ (https://www.mathworks.com/help/images/ref/sliceviewer.html). Would it be possible to have the GIBBON version renamed? Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@cberggren thanks for reporting this. Fortunately GIBBON's `sliceViewer` was really an alias for `sv3` (slice viewer 3) (and there is also `sv2`). I'll remove `sliceViewer` now to avoid this conflict, and will refer to `sv3` from now on instead.

**Comment by Kevin-Mattheus-Moerman** [comment]
@cberggren closing this now as this is fixed. Thanks.

**Comment by cberggren** [comment]
Great to know that sv3 exists! Thanks for updating.
