### ISSUE TITLE
Problems with Running Abaqus Milling Process

### ISSUE THREAD

**Issue by AbrahamChinedu** [gibbonCode/GIBBON#171]
After using Gibbon code to mesh an stl file, please how do I correctly copy out the information of the nodes and elements I need for an Abaqus simulation. I already tried to do so but the shape of the material was distorted. 

Eventually when I used the nodes and faces, I got problems with the normals when I tried carrying out an abaqus milling operation. I got this error: ***ERROR: 1 improperly defined surface(s). Please check your surface           definitions. Make sure that all surface normals point outward. To this problem, i notices some double normals on my mesh elements, whose directions were pointing in opposite directions (one direction points out of the mesh, the other directing points inwards). 

Thank you as I look forward to your advice and suggestions on how to solve this problem.

**Comment by Kevin-Mattheus-Moerman** [comment]
@AbrahamChinedu thanks for posting this issue. Unfortunately the above does not give me enough to try to help you. Is this a GIBBON issue or an Abaqus issues. As I mentioned on Mastodon, you can invert faces or elements to change the normal directions. Have you tried that?

**Comment by AbrahamChinedu** [comment]
Good morning Kevin,

I am very delighted to receive your response. I have waited so much to hear from you. 

About inverting faces or elements, please I would need directions on how to invert them. And in a case where it is required that the normals are all pointing outwards, how can it be done?

Secondly, when you say faces or elements, the usage sounds a bit confusing. I understand faces make up an element. Hope I am correct? And when I wrote the Abaqus input file, I wrote it using the TetGen gotten nodes and elements but then on importing to Abaqus, the shape of the endmill was kind of distorted, where flat smooth surfaces are expected, there were instead missing faces. I decided to use the nodes and faces and I got the a proper shape. However this created a problem. Whereas, I wanted tet elements, I now  had tri elements. So I would like to know how to ensure that the Abaqus file can be written with the nodes and the elements (tet) information and successfully get a smooth shape without missing faces.

Please Kevin, I would like to send you copies of the input files so that you understand the situation better, but at the moment I am away from my office. Once I get back to my research institute, I could share the files.

Nevertheless, I am really thankful that you replied to my inquiries. I have sought for you so much on almost every platform I know you were on. I almost give up. I am now so happy.

Kindest regards,
Abraham. 
________________________________

**Comment by Kevin-Mattheus-Moerman** [comment]
Dealt with in a video call.
