### ISSUE TITLE
Isosurface export

### ISSUE THREAD

**Issue by arojproj** [gibbonCode/GIBBON#179]
From the constructed contours per slice, how is it possible to export/save the isosurface as a .stl, .igs, .step, or any other format that can be opened in other CAD software?

**Comment by Kevin-Mattheus-Moerman** [comment]
@arojproj you can use [`contour2levelset`](https://www.gibboncode.org/html/HELP_contour2levelset.html) to convert the contours to a levelset image. 

Next you can use [`levelset2isosurface`](https://www.gibboncode.org/html/HELP_levelset2isosurface.html) to convert it to a surface. 

Finally you can use GIBBON's [`export_STL_txt`](https://www.gibboncode.org/html/HELP_export_STL_txt.html) (a bit slow and only text formatted STL based) or MATLAB's native [`stlwrite`](https://www.mathworks.com/help/matlab/ref/stlwrite.html), to export an STL file for instance. 

I'll close this one for now but let me know if you have any follow up questions.
