### ISSUE TITLE
Octave compatibility

### ISSUE THREAD

**Issue by fethio** [gibbonCode/GIBBON#23]
Hello Kevin,
Does GIBBON work/compile with Octave?
I've recently created a fork and git cloned into my laptop. I'm using Octave 4.2.2.
I get the following error message, complaining that groot cannot be found.
`>> installGibbon error: 'groot' undefined near line 14 column 15 error: called from installGibbon at line 14 column 14`

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @fethio. Thanks for posting this issue. I think in principle it is possible to get nearly all of GIBBON's functionality to work for Octave. I'd be interested in helping with this. I estimate though it would take quite a lot of time (e.g. 3 months) to do as there are many specialized functions that are not available in Octave. 
The `groot` thing you highlight is not a requirement really. I'm guessing I query the computer screen size using "graphical root", I then use that to create a large figure window. It could be changed to not use `groot` in octave. However with the `installGibbon` script there are many more issues as I built a figure window based GUI to install things. I think the GUI will not work at all. To avoid this script to a "manual install", i.e. simply add the toolbox folders and sub-folders to the path for Octave. After this there may still be missing functions though.
Let me know how you get on. I'll leave this issue open so you can post comments and progress, and perhaps others can join in. 
Thanks for testing GIBBON.

**Comment by Kevin-Mattheus-Moerman** [comment]
@fethio I recently test Octave. I could push and make nearly everything work for Octave. However, graphics and efficient visualization seems to be a major issue in Octave (very slow!). So at the moment this is hindering me from switching to Octave. I might consider the Julia language instead. 

This issue seems stale now, and as such I'll close it, but let me know if you still have questions.
