### ISSUE TITLE
The anisotropy from fiber direction doesn't work for "DEMO_febio_0015_cube_fibers_transiso"

### ISSUE THREAD

**Issue by danielcpnkimo** [gibbonCode/GIBBON#27]
Hi, recently I am trying to build a model by modifying the "DEMO_febio_0015_cube_fibers_transiso"
But when I change the "alpha" of the angle of fiber orientation from 1/3 pi to 1/2 pi and 0, The stress-strain curve always stay the same with the stress equals to -0.006718... Is there anything wrong with the fiber setting in the model. Please help and let me know how to fix it, thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @danielcpnkimo. Thanks for working with GIBBON, and for posting this. I just reran that demo and I had no issues. Both the deformation and the stress change with fiber direction. My guess is that you have an older version of FEBio, they recently had a bug that fiber directions were not appropriately set/used. Can you try to upgrade to the latest FEBio (and GIBBON) version and try again? 
If the issue persists after upgrading FEBio please send me the details of your software versions (MATLAB, GIBBON, FEBio).

**Comment by danielcpnkimo** [comment]
The problem is solved after I updated to MATLAB R2018a and FEBio 2.7.1 and the latest Gibbon codes. Thanks for your reply. I've provided my current result in the Gibbon Lobby.
https://gitter.im/GIBBONchat/Lobby


________________________________

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. BTW FEBio 2.8.0 is out now which also contains significant bug fixes.
