### ISSUE TITLE
How to assign the direction and material properties of of each fiber with Gibbon?

### ISSUE THREAD

**Issue by danielcpnkimo** [gibbonCode/GIBBON#29]
Hi, I have a matrix (8*8) of all the fiber direction in 2D in the order of their element number.
Is there a way to assign each fiber direction by their element number or their location? 
My model is a solid mixture composed of viscoelastic neo-Hookean with exponential fibers uncoupled.
I don't want to use a built in distribution to prescribe the fiber direction.

**Comment by Kevin-Mattheus-Moerman** [comment]
The following new demos (those with `_febio` are new and `_FEBio` are old demos) map fiber directions: 
`DEMO_febio_0015_cube_fibers_transiso`
`DEMO_febio_0024_active_contraction_tongue`

The former is a cube where all fibers have the same direction (but it still uses an array of fiber directions which could be spatially varying in direction) and the latter is a tongue model where each element has its own fiber direction. As you can see from these demos you create an `ElementData` entry in the `MeshData` section where you define the `mat_axis` for each element. I find this to be the most convenient way to specify the fiber directions

```matlab
%MeshData section
% -> ElementData
febio_spec.MeshData.ElementData{1}.ATTR.elem_set=febio_spec.Geometry.ElementSet{1}.ATTR.name;
febio_spec.MeshData.ElementData{1}.ATTR.var='mat_axis';

for q=1:1:size(E,1)
    febio_spec.MeshData.ElementData{1}.elem{q}.ATTR.lid=q;
    febio_spec.MeshData.ElementData{1}.elem{q}.a=a(q,:);
    febio_spec.MeshData.ElementData{1}.elem{q}.d=d(q,:);
end
```
I generally define the fiber direction to be the 3rd direction so in this case it would be along `cross(a,d)`. 

Does this make sense/answer your question?

**Comment by danielcpnkimo** [comment]
Yes, I've tried and it works. Sorry for my delayed reply.
