### ISSUE TITLE
How to pick the cylindrical inner, middle and ourter surface if I import a hex mesh from .feb file?

### ISSUE THREAD

**Issue by danielcpnkimo** [gibbonCode/GIBBON#30]
Hi, I'm trying to import the two-layer hollow cylinder with hex8 mesh from a .feb file, but after the import, I found that I can get the CE, E and V. And then I can derived from those to have F,  C. 
However, when I try to select the inner, middle and outer surface to prescribe the biphasic contact and prescribed radial boundary conditions, I found that in the Demo the radial face boundary markers are always selected by Cb generated by tetgen. I cannot find the radial prescribed face boundary markers in all the DEMO. The only assigned face boundary markers I can find are the top and bot part of the cylinder.
Is there a way to generate the face boundary markers without also importing the nodal_id of the selected boundary node set?
I had provided my .feb in one of the email before, but for clarity, I provide it here with the dropbox link here again if there is any confusion.(https://www.dropbox.com/s/q49d5c8osdtsh9c/BiphasicElasticContractionTube.feb?dl=0)

%% Access model element and patch data 
F=meshOutput.faces;
V=meshOutput.nodes;
C=meshOutput.faceMaterialID;
E=meshOutput.elements;
CE=meshOutput.elementMaterialID;
 
Fb=meshOutput.facesBoundary;
Cb=meshOutput.boundaryMarker;

**Comment by Kevin-Mattheus-Moerman** [comment]
If it is a regular cylinder you can use the normal directions to help with this. See `patchNormal`. E.g. only the top faces have an upward normal (e.g use dot product of normals with `[0 0 1]`), and so on. In this way you can remove the top and bottom boundary faces. Next you can also use the normals to find the inner and outer face sets, or use grouping (see `groupVertices`) to separate after "removal" of the top and bottom sets. Let me know if this helps.

**Comment by Kevin-Mattheus-Moerman** [comment]
@danielcpnkimo I'll close this issue as it seems "stale". But do let me know if you have more questions.
