### ISSUE TITLE
How to plot element_data that looks like using MATLAB function patch for ploting node_data

### ISSUE THREAD

**Issue by danielcpnkimo** [gibbonCode/GIBBON#31]
Hi, I've tried to import the element_data stress sx, sy, sxy and element centroid x,y,z manualy and transform the stress into radial and theta direction. However, when I tried to plot a 3D view of stress data. I found that I just saw the DEMO of plotting nodal_data using patch function and plotting stress value in 2D plot like a stress strain(or stretch) curve. Is there a way to plot element_data like stress or pressure so that I can see them like the plot shown by using patch or the plot of stress shown in Postview?

**Comment by Kevin-Mattheus-Moerman** [comment]
The new demos `DEMO_febio_00...` plot the models using the `anim8` function (see also `HELP_anim8`). Some visualize nodal data others element data. The demo `DEMO_febio_0011_cube_multi_generation` displays element data, i.e. in this case strain energy density. 

Note that I often use the `element2patch` function to convert "colors" (e.g. stresses) known on elements to "colors" on faces. You can then plot this using `gpatch` (The `gpatch` function accepts colors defined on either faces or vertices). 

Let me know if this helps.

**Comment by danielcpnkimo** [comment]
Yes, it's helpful thank you.
