### ISSUE TITLE
suggest a small change to patchNormPlot

### ISSUE THREAD

**Issue by danasolav** [gibbonCode/GIBBON#32]
If the input vertices include NaNs, no arrows will plot unless "a" is given as input.
I suggest a very quick and easy fix: replace "mean" in line 83 with "nanmean".

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for catching this. That line now reads:
```matlab
a=mean(A(~isnan(A)))*ones(1,2)/2; %half the edge length by default
```
