### ISSUE TITLE
How can I take the output of the current time step including fiber orientation and fiber stress without the stress from the neo-Hookean basis and use them to impose as the boundary condition, nodal body force or element centroid force at the next time?

### ISSUE THREAD

**Issue by danielcpnkimo** [gibbonCode/GIBBON#33]
I'm modeling the tissue mechanics with compressible neo-Hookean and exponential fibers distributed anisotropically by assigning each fiber orientation in the begining in the order of the elment number. 
What I want to do is to update the 
element centroid forces as external force at the next time step as a function of 
fiber orientation, <beta>, <theta>, <phi>, fiber stiffness, <ksi>, and fiber stretch at the current time step 
by my user-made solver using the output stress and fiber orientation at the current step as input. And then feedback from my solver the boundary condition, nodal body force or element centroid force at the next time step and solve the next time step continuously until the end time step is reached. 
How can I take the output of the current time step including fiber orientation and fiber stress without the stress from the neo-Hookean basis and use them to impose as the boundary condition, nodal body force or element centroid force at the next time? Should I make a plugin for that or there is a way to do that in MATLAB with the help of GIBBON?

**Comment by Kevin-Mattheus-Moerman** [comment]
You can export the deformation gradient tensor components, reconstruct the tensors and used them to compute the fibre directions in any desired state. In terms of fibre stress I am not sure if this is an FEBio export (@belgiansteve might be able to answer that). If not you may be able to derive it easily from your fibre constitutive formulation. Let me know if this helps.
