### ISSUE TITLE
How to remesh at each step?

### ISSUE THREAD

**Issue by danielcpnkimo** [gibbonCode/GIBBON#34]
Hi, I'm trying to replicate the model of cell mitosis of contraction of the cleavage furrow in this paper
[https://peerj.com/articles/1490/](url)
And the model I mention is this
[https://dfzljdn9uc3pi.cloudfront.net/2015/1490/1/fig-4-2x.jpg](url)
I construct a solid sphere and use the neo-Hookean material with poisson ratio 0.49 to serve as nearly incompressible material. However, when I tried to contract the central equatorial furrow region (central band), I can hardly get the convergent result as the shrinkage of radius goes up. Is there a way to do the remesh at each step with the help of Gibbon?

**Comment by Kevin-Mattheus-Moerman** [comment]
Also perhaps use an uncoupled Neo-Hookean formulation which are much more suitable for near-incompressibility. You can set a high bulk modulus e.g. typically 2 orders higher then the shear moduli. For instance by using a first order Ogden form with m1=2, and a bulk modulus which is k>>c1 (e.g. k=100*c1 or whatever needed to enforce something close enough to j=1). 
e.g.:
```matlab
        febio_spec.Material.material{1}.ATTR.type='Ogden';
        febio_spec.Material.material{1}.ATTR.id=1;
        febio_spec.Material.material{1}.c1=c;
        febio_spec.Material.material{1}.m1=2;
        febio_spec.Material.material{1}.k=k;
```

**Comment by danielcpnkimo** [comment]
Hi, thanks for the reply. Your suspicion is right. I do want to keep track of the stress and strain since the original configuration. And I'm sure that as the shrinkage of radius goes up there will be serious detortion of the region of central equatorial furrow if I don't remesh frequently enough

**Comment by danielcpnkimo** [comment]
Is there a way to have an Ogden material equivalent to the incompressible neo-Hookean material?
Because I just have the Young's modulus and poison ratio from the reference paper, but not the Ogden material.

**Comment by Kevin-Mattheus-Moerman** [comment]
You can use the `Ogden` material from FEBio and use a first order form. You can convert the Young's modulus (`E`) and the Poisson's ratio (`v`) to a shear modulus (`G`) and a bulk modulus (`k`) e.g. `k=E/3(1-2v)` and `G=E/2(1+v)`, see the conversion formulas at the bottom of [this Wikipedia article](https://en.wikipedia.org/wiki/Young%27s_modulus). Next you can set the Ogden parameters `c1=2G` and `m1=2` and `k` (see also [table in this article](https://www.semanticscholar.org/paper/Spherical-indentation-of-soft-matter-beyond-the-and-Lin-Shreiber/18a17cb737cf91d769c5287450dcf24ef0e7b042) to see how to get estimates of the initial shear modulus for several hyperelastic formulations). 
If `v=0.49` leads to an undesirably high bulk modulus and unstable behaviour try setting `k=100*c1` (2 orders of magnitude higher than the shear moduli seems to be a rule of thumb) at first and check to see if the volume ratios (`J`) are close enough to 1.

**Comment by danielcpnkimo** [comment]
Hi, thanks for the reply on material models. I saw G0=2C1 in table 1 of the article you mentioned.
The question followed may not related to Gibbon...
What I don't understand is that for all the incompressible material shouldn't all the material have infinite bulk modulus? Why is high bulk modulus leads to unstable behavior? How to evaluate the result in [this article](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.653.8987&rep=rep1&type=pdf). 

What is the material that you get the "k=100*c1"? Why is it seems to be rule of thumb?

**Comment by Kevin-Mattheus-Moerman** [comment]
Apologies I was not being able to answer this in time. This issue seems stale now, and as such I'll close it, but let me know if you still have questions.
