### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lAlejo** [gibbonCode/GIBBON#39]
Hello, I just downloaded the last gibbon update from the oficial site. I uploaded all the files to my server and when I try to run the wizard I get this error.

Parse error: syntax error, unexpected '?' in /src/Services/CoreServiceProvider.php on line 174

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for trying GIBBON and for posting this.

Are you sure this is a GIBBON related error? That path does not seem like a GIBBON path.

**Comment by lAlejo** [comment]
Yes.

It's this file https://github.com/GibbonEdu/core/blob/master/src/Services/CoreServiceProvider.php

**Comment by Kevin-Mattheus-Moerman** [comment]
That is a different project named GIBBON :) sorry I can't help
