### ISSUE TITLE
A save/import operation for anim8.m

### ISSUE THREAD

**Issue by Ipuch** [gibbonCode/GIBBON#41]
Hi,

Following #36 , I'm asking a feature to get a save/import operation for anim8.m

Sorry for the late answer,
Pierre

**Comment by Kevin-Mattheus-Moerman** [comment]
The latest patch now contains this functionality. 

To create new anim8 figures one usually uses: `anim8(hf,animStruct)`. Such anim8 figures you can save to a `.fig` file using the normal figure saving functionality. 

To reload such a saved anim8 figure use: `anim8` (i.e. no inputs) which will allow you to browse to a saved figure, or `anim8(figurePath)`, where `figurePath` defines a full path to a saved figure. Let me know how you get on.
