### ISSUE TITLE
tetGen meshing: 'The 1-th region point lies outside the convex hull'

### ISSUE THREAD

**Issue by NataCalc** [gibbonCode/GIBBON#42]
Hello,

While running tetGen with inputStruct of my STL, I get this error:
`Warning:  The 1-th region point lies outside the convex hull.
"/Users/s2986149/Desktop/GIBBON/lib_ext/tetGen/mac64/tetgen" -pq1.2AaY "/Users/s2986149/Desktop/GIBBON/data/temp/tetgenmodel.smesh": Segmentation fault
--- Done --- 08-Feb-2019 14:58:06
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--- Importing TetGen files --- 08-Feb-2019 14:58:06
Warning: /Users/s2986149/Desktop/GIBBON/data/temp/tetgenmodel.1.node import unsuccesful `

What can cause this? 

Thanks in advance,
NataCalc

[Scaphoid_improved_surface.stl.zip](https://github.com/gibbonCode/GIBBON/files/2843811/Scaphoid_improved_surface.stl.zip)
[tetGen_mesh_sizing_function_Scaphoid_Lunate.m.zip](https://github.com/gibbonCode/GIBBON/files/2843812/tetGen_mesh_sizing_function_Scaphoid_Lunate.m.zip)

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @NataCalc thanks for testing GIBBON and for posting this issue. 

Are you able to share the STL file? 

From your code I see you use: 
```matlab
V_regions=[0 0 0];
inputStruct.regionPoints=V_regions; %region points
```

The region point has to be an interior point for a certain mesh region. If you have n regions you need n interior points. Are you sure that the point with the coordinates `0,0,0` is inside your shape? 

Consider using `[F,V]=mergeVertices(F,V);` to merged nodes instead of the unique operation. 

Are you using the most recent GIBBON version?

**Comment by NataCalc** [comment]
Hi Kevin,

In my previous post I am enclosed Scaphoid_improved_surface.stl.zip and tetGen_mesh_sizing_function_Scaphoid_Lunate.m.zip. I can see them, you cannot?

I am using inhull function to check if point is inside or outside. Some sets of points are outside convex hull but when I plot convex hull, I do not see any point seating outside. 

In license its written  Version 3, 29 June 2007.

Thank you for your help.

NataCalc
[Scaphoid_improved_surface.stl.zip](https://github.com/gibbonCode/GIBBON/files/2849720/Scaphoid_improved_surface.stl.zip)

**Comment by NataCalc** [comment]
Hi Kevin,

You were right! The region point was outside the convex hull. The problem is solved.

Thank you again,
NataCalc

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. Glad to have been of assistance.

**Comment by NicolasGrandinPerea** [comment]
Hello guys !
I have a similar problem as @NataCalc  used to have: 
Warning:
C:\Users\Nicolas\Documents\MATLAB\GIBBON_matlab_toolboxes\GIBBON-9185c1c77299040b3b597ae43f553f432cfabd56\data\temp\temp.1.node
import unsuccesful 
> In importTETGEN (line 29)
  In runTetGen (line 345)
I used the GIBBON function "getInnerPoint" and checked that the point was actually inside my geometry (which is a set of nodes and elements from an abaqus file using the element2patch function)

Any help would be greatly appreciated !!

Reagards,
Nicolas

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @NicolasGrandinPerea thanks for your message. I need a bit more information.
Does tetgen create any other warning messages? Can you see if that node file is actually created? When you say elements from abaqus do you mean surface elements or solid elements? I cannot see your code but if you used `element2patch` from solid elements then you get faces for the boundary as well as the interior. This example shows how to get just the boundary faces: 

```matlab
F_elements=element2patch(E); %All faces (including interior element faces)
indBoundaryFaces=tesBoundary(F_elements,V); %Indices for boundary faces
F_boundary=F_elements(indBoundaryFaces,:); %The boundary faces
```
You then get the interior point for this subset and run tetgen for these boundary faces. 
Let me know how you get on.

**Comment by NicolasGrandinPerea** [comment]
Hi @Kevin-Mattheus-Moerman 
Thank you for your quick answer
Yes I have another error message: 
--- Importing TetGen files --- 27-Aug-2019 23:30:32
Warning:
C:\Users\Nicolas\Documents\MATLAB\GIBBON_matlab_toolboxes\GIBBON-9185c1c77299040b3b597ae43f553f432cfabd56\data\temp\brain_mesh.1.node
import unsuccesful 
> In importTETGEN (line 29)
  In runTetGen (line 345) 
--- Done --- 27-Aug-2019 23:30:32
Error using copyfile
Cannot write to destination: C:\Users\Nicolas\Desktop\brain_mesh.smesh.  Use the 'f' option to override.

Error in runTetGen (line 397)
                copyfile(fileNameTemp,fileName);
A .smesh was actually created
I'm currently using solid elements (a .inp file I split into two pieces - one for the elements & one for the vertices)

I'll try example on my script !

Thanks again for your precious help !

**Comment by NicolasGrandinPerea** [comment]
Hi @Kevin-Mattheus-Moerman 

My script is linked below if you need. 

I tried your method with using the boundary faces, however, it didn't work because the F_boundary hasn't the same dimension as F_elements:

--- Writing SMESH file --- 28-Aug-2019 14:27:58
----> Adding node field
----> Adding facet field
Error using horzcat
Dimensions of arrays being concatenated are not consistent.

Error in writeBasicSmesh (line 55)
F_field=[size(F,2).*ones(size(F,1),1) F faceBoundaryMarker(:)];

Error in runTetGen (line 259)
        writeBasicSmesh(inputStruct);

Do you have any clue ?

[github_gibbon .txt](https://github.com/gibbonCode/GIBBON/files/3550844/github_gibbon.txt)

**Comment by Kevin-Mattheus-Moerman** [comment]
Apologies I was not being able to answer this in time. This issue seems stale now, and as such I'll close it, but let me know if you still have questions.
