### ISSUE TITLE
FAILED: Log file was not created in time. FEBio likely failed prior to logfile creation! 

### ISSUE THREAD

**Issue by NataCalc** [gibbonCode/GIBBON#43]
Hi,

While running  DEMO_FEBio_active_contraction_01 in GibbonCode-Documentation, I received following  warning with failed operation:

```
--- STARTING FEBIO JOB 
Waiting for log file...
Warning: --- FAILED: Log file was not created in time. FEBio likely failed prior to logfile creation! ---
15-Feb-2019 15:50:14 
> In runMonitorFEBio (line 157)
  In Febio_active_contraction (line 270) 
Warning: Try setting FEBioRunStruct.runMode to "internal" to see potential errors prior to log file creation 
> In runMonitorFEBio (line 159)
  In Febio_active_contraction (line 270) 
--- Failed or ended! --- 15-Feb-2019 15:50:14
```
Also, following the advice I tried to update code to use febioStruct2xml
```
Warning: febStruct2febFile is depricated and will be removed in future releases. Update your codes to use
febioStruct2xml, see HELP_febioStruct2xml (furthermore febio_spec version 2.5 is recommended) 
```

I am enclosing two codes for version 2 and 2.5. I am quite confused with syntax of version 2.5. It is probably because I am not familiar (new to FEBio) with version 2. For example:

```
% What would be alternative to elementdata in version 2.5 
%febio_spec.Geometry.ElementData.mat_axis.ElementIndices=1:1:size(E,1);
%febio_spec.Geometry.ElementData.mat_axis.Basis=VF_E;
```

[Febio_active_contraction.m.zip](https://github.com/gibbonCode/GIBBON/files/2868001/Febio_active_contraction.m.zip)
[Febio_Active_contraction_v2_5.m.zip](https://github.com/gibbonCode/GIBBON/files/2868002/Febio_Active_contraction_v2_5.m.zip)

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @NataCalc thanks for posting this issue. 

Can you describe what you are trying to do? Perhaps I can recommend the best demo to focus on. 

The demo `DEMO_FEBio_active_contraction_01` is no longer available in the latest GIBBON. I would upgrade to the latest GIBBON version. 

The old FEBio versions use febio_spec 2.0 that means older FEBio version code the XML file a bit differently. The latest FEBio can still run stuff writtin in febio_spec 2.0 but it is better to switch to febio_spec 2.5. All GIBBON demos called `DEMO_FEBio_....` are for the old febio_spec 2.0, while the demos starting with `DEMO_febio_...` (note lower case febio) are for the new febio_spec 2.5. So I would focus on all the latest demos with the new febio_spec. 

In terms of active contraction check out this demo: `DEMO_febio_0024_active_contraction_tongue.m`. There you'll find that the fibers are encoded into the febio structure like this: 

```matlab
%MeshData section
% -> ElementData
febio_spec.MeshData.ElementData{1}.ATTR.elem_set=febio_spec.Geometry.ElementSet{1}.ATTR.name;
febio_spec.MeshData.ElementData{1}.ATTR.var='mat_axis';

for q=1:1:size(E,1)
    febio_spec.MeshData.ElementData{1}.elem{q}.ATTR.lid=q;
    febio_spec.MeshData.ElementData{1}.elem{q}.a=a(q,:);
    febio_spec.MeshData.ElementData{1}.elem{q}.d=d(q,:);
end
```

Hhere `a` and `d` (as discussed in the FEBio manuals) are two vectors orthogonal to the fibre direction in this case. These vectors are created using `[a,d]=vectorOrthogonalPair(V_fib)`. 

I think the above information will fix your issues. If you ever have the timeout error again it is likely FEBio did not even start. It probably gave an error for in the input file right away. If you switch to `internal` mode (i.e. `febioAnalysis.runMode='internal'; % or 'external';`) then the FEBio messages are shown in the command prompt so you can perhaps read a relevant error message. In this case however updating to the latest GIBBON and FEBio version and focusing on `DEMO_febio_0024_active_contraction_tongue.m` will likely solve your problems. 

I'll close this issue for now but let me know if you have more issues and I can reopen it.

**Comment by NataCalc** [comment]
Thanks for reopening the issue. 

I decided to start with something simple
 DEMO_febio_0001_cube_uniaxial
 
While running FEBio file I got this
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--- STARTING FEBIO JOB --- 19-Feb-2019 10:53:08
nice: febio: No such file or directory
Waiting for log file...
 
And it uses to much memory PhysMem: 14G used (2850M wired), 18G unused.
 
I do have latest versions of both, GIBBON (version 3) and FEBio (version 2.5). febioAnalysis file was created
/Users/s2986149/Desktop/FEBio-MATLAB/Febio_0001_cube_uniaxial.feb
 
Do not understand the reason why I get this message: “ nice:febio:no such file or directory
 
Maybe there is the problem with .feb file where there is no meshdata section?
 
[DEMO_febio_0001_cube_uniaxial.m.zip](https://github.com/gibbonCode/GIBBON/files/2882436/DEMO_febio_0001_cube_uniaxial.m.zip)
[Febio_0001_cube_uniaxial.feb.zip](https://github.com/gibbonCode/GIBBON/files/2882437/Febio_0001_cube_uniaxial.feb.zip)

**Comment by NataCalc** [comment]
How critical XML file for FEBio to begin with
<?xml version="1.0" encoding="ISO-8859-1"?>
followed by 
<febio_spec version="2.5">
For now generated XML file by febioStruct2xml begins with 
<febio_spec version="2.5">

**Comment by NataCalc** [comment]
Maybe this effects results which are not correct.

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @NataCalc 

If GIBBON cannot find FEBio in the path provided it tries to execute the commend `febio`, however running FEBio like that only works if you've set up an "environment variable"/alias. 

I think your FEBio path is not properly set up in MATLAB. Did you provide the full path to the FEBio executable during installation? (you can check what the current FEBio path is by running `getFEBioPath`). 

Although febio did not execute properly GIBBON/MATLAB will continue to wait (using `internal` mode and up to a user specified time), and will continue to look for the log file and track its progress. Hence when  you started the FEBio job manually yourself in your own command prompt MATLAB was able to pick up the log file and display progress. 

The thing to do is to make sure the FEBio path is set properly. If you are able to run FEBio from a MAC/OS command prompt by specifying its path directly then you should be all set after providing this path to GIBBON, i.e. GIBBON creates the exact same command and passes it either to an external command window ('external' mode) or runs it internally ('internal' mode). 

Let me know if you need more help. 

Let me know if this helps.

**Comment by NataCalc** [comment]
Hi Kevin,

Thank you for help. 

I reinstalled GIBBON correcting path to FEBio and now it works well. 

Results from compression simulation are enclosed and there is something wrong. 

![uniaxial_stress_strech_curve_compression](https://user-images.githubusercontent.com/47018678/53211997-01353c00-368f-11e9-98c8-7c21827de1e9.jpg)
![final_step_compression](https://user-images.githubusercontent.com/47018678/53212010-085c4a00-368f-11e9-837c-be5d33a75d81.jpg)
![final_step_compression0](https://user-images.githubusercontent.com/47018678/53212011-085c4a00-368f-11e9-85e5-ed71aa2367e3.jpg)

**Comment by NataCalc** [comment]
I made minor changes:

(1) In NodeSets  instead of using 
`febio_spec.Geometry.NodeSet{1}.VAL=bcSupportList_Z(:);`
use
`febio_spec.Geometry.NodeSet{1}.node.ATTR.id=bcSupportList_Z(:);`

(2) In boundary conditions settings, constrains in x, y, z directions are applied to lower face of cube with nodes where displacement in z direction and zero displacement in x and y direction are applied to upper face of cube with nodes. 

(3) Changed material properties from Ogden to Mooney-Rivlin

Now, its working well. Code is enclosed.
[DEMO_febio_0001_cube_uniaxial.m.zip](https://github.com/gibbonCode/GIBBON/files/2943890/DEMO_febio_0001_cube_uniaxial.m.zip)

**Comment by NataCalc** [comment]
Same changes have been done in Cube_discret_springs and now it's working.
[DEMO_febio_0009_cube_discrete_springs.m.zip](https://github.com/gibbonCode/GIBBON/files/2943913/DEMO_febio_0009_cube_discrete_springs.m.zip)

**Comment by NataCalc** [comment]
Btw, all your .m examples files in GIBBON-master/docs run nicely. Above mentioned errors correspond to actual examples posted in https://www.gibboncode.org/Documentation/

**Comment by Hsiang-Yj** [comment]
Would you please share the FEBio 2.5 version with me? I can't find the available software for the Gibbon, as the latest version is FEBio Studio, and the matlab running with the same warning : FAILED: Log file was not created in time. FEBio likely failed prior to logfile creation!
