### ISSUE TITLE
Indentation on biphasic slab and the coupling hydropermiability does not work

### ISSUE THREAD

**Issue by MolerYin** [gibbonCode/GIBBON#44]
Hi contributers of Gibbon,

I want to simulate spherical indentation on a biphasic slab. I tried to combine DEMO_0006 and DEMO_0018 to achieve this, so I add the biphasic properties from 0018 into 0006. However, I plot the Cauchy stress-time plot and tested many different permHydro values and found it doesn't change the plot, which means the biphasic properties do not work out.
I have no idea how to modify this. I think somewhere is wrong in line 246- 263. 
I attach my code, could anyone have experience in FEBio provide me suggestions?

Sorry I think the problem is basically from my unfamiliarity with Gibbon code for FEBio input. I appreciate for your suggestions on any link to the code introduction.

Thank you very much. Any suggestion is appreciated!

Best,
Yin
  
[Yin_febio_biphase_sphere_indentation.txt](https://github.com/gibbonCode/GIBBON/files/2874743/Yin_febio_biphase_sphere_indentation.txt)

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @MolerYin thanks for posting this and for checking out GIBBON. 

I do not have time to check this fully but my guess is this is to do with the `min_residual` control setting and perhaps your units. 

Check lines 53-127 in `DEMO_febio_0018_cube_poroelastic_ramp_hold` you'll find that I make sure the units (e.g. for density) are correct and I also set the `min_residual` value lower than FEBio's default. So perhaps try to copy more over from this demo. 

Let me know how you get on. if this is still a problem I can have a closer look next week.

**Comment by MolerYin** [comment]
Thank you @Kevin-Mattheus-Moerman for the reply!
After correcting all units to mm and add min_residual, the overall data change. However, I compare the Cauchy stress-time curve with permHydro value 7.41e-3 and 7.41e3, the result is the same.
Another thing I tried to play with is the sphereRadius, and found it can only be sampleHeight/2 rather than sampleHeight/10, or the simulation fails due to over the max_refs.
To avoid the divergence and solve the above issues, I tried to tune the mesh, but it still failed. Not sure if mesh is not the issue, or I didn't tune it the right way.

I upload the modified version here, and thank you for the comments.
[Yin_febio_biphase_sphere_indentation.txt](https://github.com/gibbonCode/GIBBON/files/2878720/Yin_febio_biphase_sphere_indentation.txt)

**Comment by MolerYin** [comment]
Hi @Kevin-Mattheus-Moerman ,

I successfully coupling the biphasic with indentation now, and trying to add biphasic+viscoelastic properties together. I found a script BVE_UCrix.feb, and it successfully runs the latest FEBio version 2.8.5
I follow the structure and modify the Material session, from line 295-299 it should be:
febio_spec.Material.material{1}.solid.elastic.solid.ATTR.type='neo-Hookean';
febio_spec.Material.material{1}.solid.elastic.solid.ATTR.name='viscoelastic solid';
febio_spec.Material.material{1}.solid.elastic.solid.E=E1;
febio_spec.Material.material{1}.solid.elastic.solid.v=v1;
febio_spec.Material.material{1}.solid.elastic.solid.density=d; 

However, it tells me invalid value "elastic" for attribute "elastic.type"

If I change every solid.elastic.solid to solid.elastic as the attached file now, then it can run, but the relaxation time t1 for neo-Hookean doesn't work.

Do you have experiences on coupling different materials properties in the script? I think it is because I do something wrong with the tree structure in FEBio.

If anyone has experiences on this, any comment or suggestion is appreciated.
Thanks in advance.

Best,
Yin

 
[BVE_UCrlx.feb.txt](https://github.com/gibbonCode/GIBBON/files/2920174/BVE_UCrlx.feb.txt)
[Yin_poroviscoelastic_cube_ramp_hold.txt](https://github.com/gibbonCode/GIBBON/files/2920178/Yin_poroviscoelastic_cube_ramp_hold.txt)

**Comment by Kevin-Mattheus-Moerman** [comment]
I had a quick look. Can you check if this works: 

To get this in your .feb file:
```XML
	<Material>
		<material id="1" name="Biphasic-Viscoelastic" type="biphasic">
			<phi0>0.2</phi0>
			<solid type="viscoelastic">
				<g1>0.5</g1>
				<t1>3000</t1>
				<elastic type="solid mixture">
					<solid type="neo-Hookean">
						<density>1</density>
						<E>0.5</E>
						<v>0</v>
					</solid>
					<solid type="ellipsoidal fiber distribution">
						<beta>2,2,2</beta>
						<ksi>5,5,5</ksi>
					</solid>
				</elastic>
			</solid>
			<permeability type="perm-Holmes-Mow">
				<perm>0.001</perm>
				<M>3</M>
				<alpha>2</alpha>
			</permeability>
		</material>
```

I think you need to code it like this:

```matlab
%Viscous part
febio_spec.Material.material{1}.ATTR.type='biphasic';
febio_spec.Material.material{1}.ATTR.name='Biphasic-Viscoelastic';
febio_spec.Material.material{1}.ATTR.id=1;
febio_spec.Material.material{1}.phi0=0.2;
febio_spec.Material.material{1}.permeability.ATTR.type='perm-Holmes-Mow';
febio_spec.Material.material{1}.permeability.perm=0.001; 
febio_spec.Material.material{1}.permeability.M=3; 
febio_spec.Material.material{1}.permeability.alpha=2; 

%Solid part
%-> Viscoelastic part
febio_spec.Material.material{1}.solid{1}.ATTR.type='viscoelastic';
febio_spec.Material.material{1}.solid{1}.g1=0.5;
febio_spec.Material.material{1}.solid{1}.t1=3000;
febio_spec.Material.material{1}.solid{1}.density=1e-9;

%-> Elastic part
febio_spec.Material.material{1}.solid{1}.elastic{1}.ATTR.type='solid mixture';
febio_spec.Material.material{1}.solid{1}.elastic{1}.solid{1}.ATTR.type='neo-Hookean';
febio_spec.Material.material{1}.solid{1}.elastic{1}.solid{1}.density=1e-9;
febio_spec.Material.material{1}.solid{1}.elastic{1}.solid{1}.E=0.5;
febio_spec.Material.material{1}.solid{1}.elastic{1}.solid{1}.v=0;
febio_spec.Material.material{1}.solid{1}.elastic{1}.solid{2}.ATTR.type='ellipsoidal fiber distribution';
febio_spec.Material.material{1}.solid{1}.elastic{1}.solid{2}.beta=[2 2 2];
febio_spec.Material.material{1}.solid{1}.elastic{1}.solid{2}.ksi=[5 5 5];
```

**Comment by MolerYin** [comment]
Thank you @Kevin-Mattheus-Moerman , it works beautifully now! I stay with the solid mixture and just block ellipsoidal fiber distrubtion, and all work now.

Best,
Yin
