### ISSUE TITLE
Stitching 2 surfaces together

### ISSUE THREAD

**Issue by NataCalc** [gibbonCode/GIBBON#45]
Hello Kevin,

I am trying to use delaunayZip function to stitch 2 surfaces together along their edge. It fails with following message:

`Operands to the || and && operators must be convertible to logical scalar values.

Error in delaunayZip (line 226)
            if indClosest~=1 && indClosest~=numel(indListSub2)

Error in STEP1 (line 202)
[F,V,C]=delaunayZip(F_SLIL_Lunate,V_SLIL_Lunate,F_SLIL_Scaphoid,V_SLIL_Scaphoid,inputStruct);`

What does it mean?

**Comment by Kevin-Mattheus-Moerman** [comment]
It probably means that one of these lists `indClosest~=1 && indClosest~=numel(indListSub2)` is not of the same type, or empty, or NaN. 

Would you be able to send me the surfaces so I can have a look at what is going on?

**Comment by NataCalc** [comment]
Here are two surfaces (Faces1, Vertices1) and (Faces2, Vertices2).

Faces1 =
    13 17 4
    19 18 17
    11 6 2
    15 9 6
     4 10 13
    15 13 10
     1 3 11
     8 11 3
    11 8 14
    15 7 9
    15 10 7
    13 15 19
     6 19 15
    17 13 19
     2 1 11
     5 11 14
    12 11 5
    19 16 18
    12 16 11
     6 11 16
     6 16 19
Vertices1 =
   -0.9373 7.6916 -648.2637
   -0.8579 7.4760 -647.4918
   -1.0501 7.7414 -649.0116
   -0.5848 8.6325 -645.2425
   -0.7854 9.0888 -648.1130
   -0.6972 7.9258 -646.4067
   -0.7373 8.1480 -645.3852
   -0.9621 8.4652 -649.0186
   -0.6751 7.9839 -645.8602
   -0.6876 8.4840 -645.0850
   -0.7412 8.6153 -647.4756
   -0.8000 9.1263 -647.5507
   -0.5211 8.8157 -645.8041
   -0.8117 8.8818 -648.3801
   -0.5950 8.4869 -645.8868
   -0.6234 9.1628 -646.8750
   -0.4994 9.1520 -645.8782
   -0.5593 9.3296 -646.3773
   -0.5715 8.9580 -646.3603
Faces2 =
     7 5 4
    14 13 10
    10 9 12
     8 3 5
    10 1 9
    10 4 1
    10 12 15
     2 8 11
    10 7 4
    10 15 14
    10 13 11
     8 7 10
     2 11 6
    11 8 10
     3 8 2
     5 7 8
Vertices2 =
    1.3932 8.2533 -643.9472
    1.5729 7.7014 -647.2515
    1.3217 7.6907 -646.4751
    1.3211 8.3274 -644.4461
    1.3071 8.0786 -645.7357
    1.7985 7.3586 -648.2582
    1.6118 8.5291 -644.9382
    1.8661 8.1444 -646.7384
    2.4238 8.5583 -643.3868
    2.5365 8.7506 -644.2029
    2.6570 8.2030 -647.6214
    2.9696 8.7519 -643.3416
    3.5279 8.9550 -646.0495
    4.2873 8.9684 -646.1083
    4.3092 9.1687 -643.8436

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by NataCalc** [comment]
What it can be?

```
Unable to perform assignment because the left and right sides have a different number of elements.

Error in edgeListToCurve (line 51)
        indList(q)=ind3;
```

**Comment by Kevin-Mattheus-Moerman** [comment]
I've had a look at your surfaces. I cannot see what the other inputs you provide are (entries in `inputStruct`) but if I create appropriate indices of boundary curves to stitch I do not get an error.

Can you explain what you are trying to do here? Usually delaunayZip is used to stitch two surfaces together which can be merged by "zipping" or closing a small separation between them. I get the impression you want to instead create a surface from one entire boundary to the other boundary. This can be done too but not with this function.

**Comment by NataCalc** [comment]
What do you mean by appropriate indices of boundary curves?
You are right, I want to create a surface from one entire boundary to the other boundary. What kind of function do you use for it?

**Comment by NataCalc** [comment]
I am still wondering to know what is wrong with these two surfaces. I was trying manually to rewrite edgelistcurve thinking that it can help

ind1 =

    13
    10
     7
    11
     2
     3
     4
     9
     8
    12
    14
    13


ind2 =

    12
     9
     1
     4
     5
     3
     2
     6
    11
    13
    14
    15
    12

Error using vertcat
Dimensions of arrays being concatenated are not consistent.

Does it mean that dimension of ind1 and ind2 have to be the same?
