### ISSUE TITLE
DEMO_febio_0024_active_contraction_tongue

### ISSUE THREAD

**Issue by NataCalc** [gibbonCode/GIBBON#48]
Hello Kevin,

Ogden unconstrained + fiber-exp-pow is not working in Ogden unconstrained + fiber-exp-pow in DEMO_febio_0024_active_contraction_tongue. 

Regards

**Comment by Kevin-Mattheus-Moerman** [comment]
Fixed in latest version. Thanks for spotting this. I specified a bulk modulus on the fiber term which is not allowed.

**Comment by NataCalc** [comment]
Thanks for answer. 

For "Ogden unconstrained" I changed "k" to "cp", and removed "k" from "fiber-exp-pow". (For details, I checked the user manual (https://help.febio.org/FEBio/FEBio_um_2_9/index.html), section 4.1.3.8 and 4.1.3.19 for). With these changes, the model runs for me.
