### ISSUE TITLE
There is two anim8 toolbar when I reload a .fig

### ISSUE THREAD

**Issue by Ipuch** [gibbonCode/GIBBON#49]
Hi,
Following #41, Thank you for adding this functionality this is very useful.
Nevertheless, I have to report a minor bug on the function.

There is two anim8 toolbar when I reload a .fig
![image](https://user-images.githubusercontent.com/40755537/58568385-7ab36c00-8234-11e9-8b70-bbcc04cf3dad.png)

The problem might be at the line 91
```
hb = findall(hf,'Tag',toolbarTag); % hb = findall(hf,'Type','uitoolbar');
if ~isempty(hb) 
    delete(hb)
end
```

Also, the loading is very nice but I'm not able to enjoy the features of cFigure.
Is possible to develop an opencFigure.m-like function ?

Kind regards,

Pierre

**Comment by Kevin-Mattheus-Moerman** [comment]
I cannot replicate this unless I load an "old" figure. Are these new figures you saved? Or are these figures you saved before I added this feature? If these are "old" figures then it cannot find that current toolbar so creates a new one (I recently added a tag to the anim8 bar to find it). If needed I can add that it just deletes all toolbars which are not of the type `FigureToolBar` (which is the normal toolbar). 

Can you check the following for an anim8 figure:
```matlab
hf=gcf; %Get current figure handle
hb = findall(hf,'Type','uitoolbar'); %Find handles to uitoolbars
```
Next can verify you get this if you type `hb` in a command window?
```
hb = 
  2×1 Toolbar array:
  Toolbar    (anim8_toolbar)
  Toolbar    (FigureToolBar)
```
Next this should allow one to get the handle for the normal toolbar: `findall(hf,'Tag','FigureToolBar')` 
And this should allow one to get the handle for the anim8 toolbar (for a new anim8 figure):  `findall(hf,'Tag','anim8_toolbar')`

If you upgrade GIBBON you'll see I did add that it also reloads the `vcw` (view control widget) and `efw` (export figure widget) buttons.

**Comment by Kevin-Mattheus-Moerman** [comment]
The latest version should fix the double toolbar problem (I now remove all but the default bar). Can you confirm it works?

**Comment by Ipuch** [comment]
It works perfectly !
Thank you very much !
