### ISSUE TITLE
Running Gibbon on unix cluster

### ISSUE THREAD

**Issue by hkollech** [gibbonCode/GIBBON#53]
Hi, 
I am trying to run gibbon on unix supercomputers and I am getting the error below about permission.
 **/bin/bash: /ihome/jvandegeest/hik27/CSMMD_CRC_job_submission_template/geometry/GIBBON-master/lib_ext/tetGen/lin64/tetgen: Permission denied**
 I tried changing the permission of the GIBBON-master folder but that didn't resolve the issue. Please advise.
I also attached the file below.

Thanks, 
hirut
[error.log](https://github.com/gibbonCode/GIBBON/files/3622694/error.log)

**Comment by Kevin-Mattheus-Moerman** [comment]
@hkollech. This sometimes happens. The solution is has always been to make sure that all permissions are set properly for all the programs/files/folders involved. Can you make sure the TetGen executable has all the right permissions? It will try to write files within the GIBBON folder. 

![Screenshot from 2019-09-19 09-57-10](https://user-images.githubusercontent.com/8392709/65229285-efe8cc80-dac3-11e9-8488-714125938691.png)

**Comment by hkollech** [comment]
thank you! that solved the issue.
