### ISSUE TITLE
Bug in anim8

### ISSUE THREAD

**Issue by danasolav** [gibbonCode/GIBBON#54]
It seems like a new bug was introduced in the last update to anim8 (with the new slider)
If there is only 1 time step, anim8 throws this error:
```
Error using matlab.ui.control.UIControl/set
Error setting property 'SliderStep' of class 'UIControl':
Slider step line increment must be between 0 and 1.

Error in anim8 (line 80)
set(hSlider,'Value',sliceIndexI,'Min',1,'Max',numel(animTime),'SliderStep',[1/(numel(animTime)-1) 1/(numel(animTime)-1)]);
```

It hasn't been a problem until the last update.

Thanks,
Dana

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks. I'll check this shortly.

**Comment by Kevin-Mattheus-Moerman** [comment]
I think this has been solved (actually a long time ago but I forgot to mention this here). I'll close this issue for now but let me know if the problem persists for you.
