### ISSUE TITLE
activating view control widget automatically

### ISSUE THREAD

**Issue by jpv20** [gibbonCode/GIBBON#55]
Hi Kevin,

simple question - how do you activate the view control widget automatically every time i run gibbon code?  its likely very simple and having to click on this button on every figure is very annoying.

thanks!
j

**Comment by Kevin-Mattheus-Moerman** [comment]
Ah right, good feature request. It's the button in the toolbar or the 'v' key for now. I can add the automatic feature easily but have to think about it for a bit. Currently the view control widget axis settings are only suitable when all axes have the same units (i.e. `axis equal`). Perhaps I can switch it on when you use `axisGeom` which is for geometry with equal axis properties.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jpv20 I finally decided to implement something to address this. I've just added a function called `gdrawnow` which acts the same as `drawnow` except it also triggers the start of the `vcw` widget if present for the current figure window. Example: 

```matlab
[X,Y,Z]=peaks(25); % Some example data
cFigure; %Opens a cFigure window which contains the vcw button
surf(X,Y,Z); %Visualize something in an axis
axisGeom; %Set axis options for geometry viewing
gdrawnow; %drawnow + vcw activation
```
See also the updated documentation: `HELP_gdrawnow` and `HELP_vcw`. 

I'll close this issue for now but let me know if there are issues/questions and I'll reopen it.

**Comment by jpv20** [comment]
wow thanks so much...works great!

**Comment by Kevin-Mattheus-Moerman** [comment]
@jpv20 I've (just now) made further bug fixes to `vcw`, let me know if you've tested it and notice anything weird. I fixes scroll based zooming now too and `vcw` should work for axes with different aspect ratios (different than 1 1 1).

**Comment by jpv20** [comment]
excellent...just downloaded it again!

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. Out of interest, @jpv20 do you always download the .zip file or do you use `git clone https://github.com/gibbonCode/GIBBON.git` and `git pull` to get only the latest changes?

**Comment by jpv20** [comment]
i am afraid i am a zip file downloader....never used git before...need to learn....instructions available for a Mac user?  i am sure its easy - just never done it....

**Comment by Kevin-Mattheus-Moerman** [comment]
Git for Mac: https://git-scm.com/download/mac
Once installed you can use (go to a folder and execute): `git clone https://github.com/gibbonCode/GIBBON.git` to clone GIBBON to that folder
You can then use GIBBON as usual from the location. If you want to get the latest changes you can check if stuff has been changed with `git status` (also shows changes you made). Then if you want to get the changes I made you can do `git pull`. 
So effectively all you need to learn is `git pull`, to only pull in my changes. 

More complex git stuff is needed when you've made changes too. This may lead to a "merge conflict". If you want to resolve the merging conflict (merge my changes with your changes) then you need to do more fancy git. If you want to just discard your changes then you can do: 
`git reset --hard HEAD`
After that you can you `git pull` again without conflicts (your changes were deleted). 

The nice thing about git is that you can push changes to GitHub too and start contributing to GIBBON. :) 

Let me know if you have questions.
