### ISSUE TITLE
Inverse fitting using Febio

### ISSUE THREAD

**Issue by NataCalc** [gibbonCode/GIBBON#57]
Hi Kevin,

I am adapting your inverse FEA cube uniaxial to my case study. In Febio inverse cases syntax is as follows: febio2 -i oi01.feb -s op01.feb , where oi01 is actual test (for example tensile) and op01 is inverse fitting. I have not noticed that your code does not create such optimisation file, is it true?

While running the inverse fitting code for my case study I got this message:

```
Local minimum possible.
lsqnonlin stopped because the final change in the sum of squares relative to 
its initial value is less than the selected value of the function tolerance.

<stopping criteria details>

Optimization stopped because the relative sum of squares (r) is changing
by less than options.FunctionTolerance = 1.000000e-06.

Optimization Metric                                  Options
relative change r =   7.49e-12             FunctionTolerance =   1e-06 (selected)
```

Do I have to reduce the function tolerance or there is something wrong with my code?

I have enclosed the Fig.png with first step of optimisation where experimental and simulated data of stress versus strain are listed and in Fig1.png the final step where, obviously, results show very poor optimisation. 
![Fig](https://user-images.githubusercontent.com/47018678/68350304-9a3bb280-014b-11ea-97da-d37a07c260a6.png)
![Fig1](https://user-images.githubusercontent.com/47018678/68350314-9f98fd00-014b-11ea-9b9e-4a3ff8cde773.png)

Cheers,
Nataliya

**Comment by Kevin-Mattheus-Moerman** [comment]
I think this issue is now resolved as we had several Skype meetings on this topic
