### ISSUE TITLE
xmlwrite_xerces - potential issue with later Matlab versions

### ISSUE THREAD

**Issue by aaronsfox** [gibbonCode/GIBBON#60]
Hi Kevin,

I came across an issue in the xmlwrite_xerces function when using febioStruct2xml to write an FEBio 'file. At line 48 the code uses 'set(objOutputFormat,'Indenting','on;)' which causes an error in my Matlab R2019b. Some comments on this page - https://au.mathworks.com/matlabcentral/fileexchange/12907-xml_io_tools - suggest changing the 'on' to the boolean operator true in at least R2018b onwards, and this solved the issue for me.

Thought I would mention this here as a potential issue for users on later versions of Matlab by the looks of it.

Regards,

Aaron

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @aaronsfox, thanks for posting this. Are you perhaps using a very old version of GIBBON? 
I check that code and in it I found one of my own comments from 2017 saying: 
```matlab
% 2017/06/26 Kevin Moerman fixed code to work with MATLAB 2016,2017. This
% involved changing a setting from 'on' (string) to 1 (scalar)
```
Then later in the code (now line 69) it says: 
```
set(objOutputFormat,'Indenting',1); %KMM: Changed from set(objOutputFormat,'Indenting','on');
```
Using `1` is likely equivalent to `true`. 

FYI if you are using an old version and would like to upgrade to the latest version please do let me know if you need help. 

Kevin

**Comment by aaronsfox** [comment]
Hi Kevin,

Yes I suspect this was the case. I was having issues with Git on this computer and hence had to download the zipped version from the website - so it seems that issue is still present in that code.

Aaron

**Comment by Kevin-Mattheus-Moerman** [comment]
Where do you download from? I just checked and the website link here: https://www.gibboncode.org/Installation/#Download does offer the most recent version. Did you download some archived version from Zenodo?

**Comment by aaronsfox** [comment]
Hmmm I clicked the 'Download .zip file directly' link on the installation page yesterday and that's what came through - I'm now beginning to wonder whether I have an older version buried on this computer somewhere that was getting preferentially directed to when I was debugging my issue.

**Comment by Kevin-Mattheus-Moerman** [comment]
I'll close this issue for now but let me know if you need more help here. Thanks again for posting.
