### ISSUE TITLE
Feature request: Triangle meshing with interior must points

### ISSUE THREAD

**Issue by danasolav** [gibbonCode/GIBBON#61]
It would be great to have an option to force the mesh to include some interior must points, similar to the existing option of including must points on the curve when meshing the interior.
Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @danasolav. Thanks for posting this issue. 

The option of adding `interiorPoints` has now been added to `regionTriMesh2D`. The [documentation](https://github.com/gibbonCode/GIBBON/blob/master/docs/HELP_regionTriMesh2D.m) has also been updated (see the last example). 

Can  you test and report back if this is what you wanted?

**Comment by danasolav** [comment]
Hi @Kevin-Mattheus-Moerman 
It works, but not perfectly. I needed to allow resampling of the curve to achieve the right mesh size, but then it moved my corner points as well, so it would be helpful to have must points on the curve AND interiorly.
Also, some triangles are of low quality, despite the 250 smoothing iterations.
See this figure for example: 
![mesh](https://user-images.githubusercontent.com/30727421/81117774-b56a5d80-8ef5-11ea-8576-485cd3d1abe9.jpg)

**Comment by Kevin-Mattheus-Moerman** [comment]
I think I fixed it now. `regionTriMesh2D` and documentation have been updated. You can now add interior and boundary must points. 

![Screenshot from 2020-05-06 14-29-09](https://user-images.githubusercontent.com/8392709/81182714-1c474f80-8fa6-11ea-8235-0ac305f95fc6.png)

I addressed the mesh quality issue by removing standard mesh points that are introduced too close to the must points. By default it removes them if they are closer than half the point spacing to a must point (but you can override to make it bigger/smaller by setting: `inputStructure.removeDistInterior`). 

Can you test this and report back?

**Comment by Kevin-Mattheus-Moerman** [comment]
@danasolav any luck testing this?

**Comment by Kevin-Mattheus-Moerman** [comment]
@danasolav I'll close this for now but let me know if you have any issues and I'll reopen it.
