### ISSUE TITLE
Surface extension

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [gibbonCode/GIBBON#63]
Surface extension was [requested recently](https://twitter.com/aaron_s_fox/status/1245445201784524801?s=20) by @aaronsfox. I'm posting this feature request here for "book keeping".

**Comment by Kevin-Mattheus-Moerman** [comment]
This is now addressed in 49cc1ee (I linked to the wrong issue in the commit message). 
I added a function called `patchExtend` and the associated documentation HELP_patchExtend.

Note I implemented 5 different extension methods. I hope one of them is what you had in mind. T

he surface extension has some limitations. If the surface tangent vectors at the edges (see visualizations in the documentation) are convergent (i.e. they point at each other) then the surface might "pinch" together or even cross over and become invalid. The surface extension is also rather sensitive to other noise (in terms of shape) at the boundary to be extended, i.e. any irregularities get amplified by the extension. Smoothing might suppress such issues. 

@aaronsfox Please test this new functionality and let me know how you get on.

**Comment by aaronsfox** [comment]
Sorry for the delay in response here @Kevin-Mattheus-Moerman. I finally got to test this out and it works well for some simple applications I've applied it to. I've got some more complex approaches to test it on in the near future, where I may end up using a combination of this and the sweep loft feature. I'll let you know if anything interesting comes of this. Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
@aaronsfox sounds good. Let me know if you need help. I'd be happy to chat if you get stuck.

**Comment by Kevin-Mattheus-Moerman** [comment]
I'll close this issue for now but let me know if you need more help/changes and I'll reopen it.
