### ISSUE TITLE
Mammography problem

### ISSUE THREAD

**Issue by sergioblancoib** [gibbonCode/GIBBON#66]
Dear Kevin,
I am writting you because I have the same issue with the mammography problem that had André in a closed issue (I wrote there too). If I run the code as it is in gibboncode, I am able only to run four steps before it crashes (around time 0.4). If I see the postprocess (i am sending the picture) I see a total penetration inside the breast. I've tried with previous versions of febio but I got the same results. I've tried also to change the contact penalty with the similar results.

Could you please help me? Is there samething that I am missing?

Thank you very much,

Sergio

![image](https://user-images.githubusercontent.com/16956468/82553230-f011fe00-9b63-11ea-81fb-249e673bdd65.png)

**Comment by sergioblancoib** [comment]
Dear Kevin,
Hello again. I think the problem is with my configuration or my machine. One of my students has been able to run the simulaltion without problems in his machine. 

Best wishes,

Sergio

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @sergioblancoib. What version of FEBio are you using? It seems to be related to the FEBio contact formulations which did change quite bit over the last 2 years, so perhaps you are using an old FEBio version? 
Can you upgrade GIBBON and also FEBio and try again? 
Let me know how you get on.

**Comment by Kevin-Mattheus-Moerman** [comment]
Do you still have an issue with this demo?

**Comment by Kevin-Mattheus-Moerman** [comment]
I'll close this issue for now but happy to reopen if the issue persists.
