### ISSUE TITLE
quick question regionTriMesh2D

### ISSUE THREAD

**Issue by jpv20** [gibbonCode/GIBBON#73]
Kevin,

in this example:
https://www.gibboncode.org/html/HELP_regionTriMesh2D.html

what would be the correct syntax to require all boundary nodes to be 'must'.  1:10:end works fine.  i tried this which is close

inputStructure.regionCell={V};
inputStructure.pointSpacing=0.05;
inputStructure.resampleCurveOpt=1;
inputStructure.plotOn=0;
inputStructure.mustPointsInner=Vm;
%inputStructure.mustPointsBoundary=V(1:10:end,:);
inputStructure.mustPointsBoundary=V(1:2:end,:);
inputStructure.smoothIterations=250;

but the mesh density is reduced on the boundary as a result.  

thanks!
jonathan

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @jpv20 apologies for the delay. Do keep posting reminders if I am slow. 

I'll have to have a look at this on Monday but perhaps you can also check:
```
inputStructure.resampleCurveOpt=0
```
That would force it to not resample and therefore keep your input boundary. Unless you want additional nodes. Again I'll have a look on Monday but let me know if this is close to what you want.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jpv20 I've expanded the documentation to include two types of handling of using an all must-point boundary (i.e. with and without resampling of the boundary). See the new `HELP_regionTriMesh2D` file. 

I'll close this issue for now but let me know if you still have questions.
