### ISSUE TITLE
XML format incompatible with FEBio?

### ISSUE THREAD

**Issue by bluefog21** [gibbonCode/GIBBON#74]
I have a question regarding what seems to be a problem with the xml format I export from MATLAB using Gibbon. To give a little context, I am exporting a FE model from FEBio, modifying it in MATLAB, and exporting it back out. I am trying to assign a specific Young’s Modulus to each element in my mesh, and this seemed to be the best way. The problem is, the formatting of the xml code is slightly different:
Exported from FEBio (read using notepad, originally an .feb file): 
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<febio_spec version="3.0">
	<Module type="solid"/>
	<Control>
		<analysis>STATIC</analysis>
		<time_steps>10</time_steps>
		<step_size>0.1</step_size>
		<solver>

			<max_refs>15</max_refs>
			<max_ups>10</max_ups>
			<diverge_reform>1</diverge_reform>
			<reform_each_time_step>1</reform_each_time_step>
			<dtol>0.001</dtol>
			<etol>0.01</etol>
			<rtol>0</rtol>
			<lstol>0.9</lstol>
			<min_residual>1e-20</min_residual>
			<qnmethod>BFGS</qnmethod>
			<rhoi>0</rhoi>
		</solver>

```
The xml (.feb) file is read in using `xml2struct`: https://www.mathworks.com/matlabcentral/fileexchange/28518-xml2struct, modified, and exported from MATLAB using `febioStruct2xml`. Then, reading the modified version of the xml file, it looks like this: 
 
```
<?xml version="1.0" encoding="UTF-8"?>
<febio_spec>
    <!--Created using GIBBON, 10-Oct-2020 20:03:21-->
    <febio_spec>
        <Module>
            <Text/>
            <Attributes>
                <type>solid</type>
            </Attributes>
        </Module>
        <Control>
            <analysis>
                <Text>STATIC</Text>
            </analysis>
            <time_steps>
                <Text>10</Text>
            </time_steps>
            <step_size>
                <Text>0.1</Text>
            </step_size>
            <solver>
                <max_refs>
                    <Text>15</Text>
                </max_refs>
                <max_ups>
                    <Text>10</Text>
                </max_ups>
                <diverge_reform>
                    <Text>1</Text>
                </diverge_reform>
                <reform_each_time_step>
                    <Text>1</Text>
                </reform_each_time_step>
                <dtol>
                    <Text>0.001</Text>
                </dtol>
                <etol>
                    <Text>0.01</Text>
                </etol>
                <rtol>
                    <Text>0</Text>
                </rtol>
                <lstol>
                    <Text>0.9</Text>
                </lstol>
                <min_residual>
                    <Text>1e-20</Text>
                </min_residual>
                <qnmethod>
                    <Text>BFGS</Text>
                </qnmethod>
                <rhoi>
                    <Text>0</Text>
                </rhoi>
            </solver>
```
 
This form is not recognized my FEBio, and I get error messages where it does not recognize <febio_spec> and the like, which is understandable as nothing like that exists in the original exported xml code, but even if I replace it with the original lines of code, FEBio gives the message "skipping lines 5,6,9,47 etc", opening a blank project. 
I’m not sure if I’m doing something wrong, or if this path of doing things is not reasonable, but I’d really appreciate any help with this!

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @bluefog21 thanks for posting this issue. In short, the problem here is not with GIBBON but with that import function `xml2struct` behaving differently from my `febioStruct2xml` function. There is not one unique way to convert XML files to structures and back and the two codes have made different decisions about how to treat attributes and values. What is needed is a proper import function of an XML file to my particular `febioStruct` implementation, perhaps a special adjusted version of `xml2struct`. 

MATLAB structures and XML files are difficult entities to combine. The main issue is how to handle the attributes. Essentially structures are like tree structure with levels that split and split and split. XML files also have this, which is denoted by these nested things that indent deeper and deeper. However XML files have one annoying thing on top of that which MATLAB structures do not have, and that is "attributes". Attributes are not a split in the structure but "add something" about the current branch. i.e. I use a structure field called `ATTR` to act as a "flag" to tell my code there's an attribute coming:  
```matlab
%febio_spec version
febio_spec.ATTR.version='2.5';

%Module section
febio_spec.Module.ATTR.type='solid';
```
Which `febioStruct2xml` correctly translates to:
```xml
<febio_spec version="2.5">
	<Module type="solid"/>
....
Where you can see `version` and `type` say something about their branch/subfield `febio_spec` and `Module` respectively, and are thus attributes. 

This means that `febio_spec` is like the trunk, `Module` needs to become a new split in tree, or a subfield (indented in XML view). Then `ATTR` is detected as a flag to tell me what follows is no longer subfields but an attribute or property about the current (`Module`) subfield (FYI I also use the flag `VAL` to denote a value). 

It seems that `xml2struct` function does not import it to have this. Instead it creates `Text` fields in the MATLAB structure for anything like a value, and then also adds additional `Attributes` fields in the structure when it is an attribute. 

To fix this one could create a special version of `xml2struct` and whenever it says `Text` as a field convert it to `VAL`, and whenever it says `Attribute` to rename it to `ATTR` (I choose `ATTR` and `VAL` to be fields which I hoped nobody would ever actually implement in FEBio as fields in the XML, it seems to me `Text` and `Attribute` do sound more dangerous to use as "flag" keywords as they might pop up in some application). 

If you want to go the route of changing `xml2struct`, would you be able to attempt this yourself? If not this will be added to the list of future enhancements. 

Alternatively the easiest thing to do instead is to perhaps code your model in MATLAB in full and export a whole new XML. GIBBON supports spatially varying materials too (see `DEMO_febio_00014_cube_varying_material` and `DEMO_febio_0027_layer_spatially_varying_material`)

**Comment by Kevin-Mattheus-Moerman** [comment]
@bluefog21 I'll close this issue for now but please let me know if you have any related issues or want me to reopen this to discus this further.
