### ISSUE TITLE
Error writing to XML - FEBio

### ISSUE THREAD

**Issue by imlikeTT** [gibbonCode/GIBBON#75]
Hi Everyone!

I am currently trying to run a basic simulation through GIBBON to FEBio but having a little bit of trouble with it writing to an XML file format. Any assistance would be appreciated! MATLAB_to_FEBio is the name of the code I am using to run.

Error` using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in cell2txtfile (line 63)
        fprintf(fid,'%s\r\n', T{:});

Error in febioStruct2xml>textModeElementAttributeParse (line 321)
cell2txtfile(fileName,totalTextCell,0,0); %Export to text file

Error in febioStruct2xml>febioStruct2xmlStep (line 178)
                            [domNode,rootNode]=textModeElementAttributeParse(domNode,rootNode,currentFieldName,attributeStruct,arrayDataSet,numArray,fieldNameSetSub,fileName,arrayParseMethod);

Error in febioStruct2xml>recursiveElementParse (line 228)
        [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,parseStructSub,optionStruct,fileName); %Add whatever is nested in
        here

Error in febioStruct2xml>febioStruct2xmlStep (line 210)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml>recursiveElementParse (line 223)
    [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,currentFieldValue,optionStruct,fileName); %Add whatever is nested in
    here

Error in febioStruct2xml>febioStruct2xmlStep (line 210)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml (line 78)
[domNode]=febioStruct2xmlStep(domNode,rootNode,parseStruct,optionStruct,fileName);

Error in MATLAB_to_FEBio (line 421)
febioStruct2xml(febio_spec,febioFebFileName);

**Comment by Fireedman** [comment]
Hi, which demo are you trying to run?

**Comment by imlikeTT** [comment]
@Fireedman I am actually not following a particular demo. Is this forum specifically for demo related issues?

**Comment by Fireedman** [comment]
Nop, but I have had similar warnings that you described by creating/open XML files but I was following the procedure described in all demos. My solution was to declare a whole new section to create/open the XML file. I was using matlab live script version 2020 and I read that command fprintf was an old version of fopen that was no compatible with live scripts

**Comment by imlikeTT** [comment]
I tried playing around with the fprintf and it seems to be passing the initial issue now! but now it is getting stuck at this:

FATAL ERROR: the value for tag "tri3" is invalid (line 121840) 

Does this mean there is a problem with the face?

**Comment by Fireedman** [comment]
One trouble solved... and a completely new start :D, maybe the trouble is the way that you declare the variable in matlab, In Previous issues @Kevin-Mattheus-Moerman explain that the XML converter is designed in a specific way to declare variables in febio format. if you can verify the way that you declared it maybe can fix the trouble. could you post the code or upload the file to verify it

**Comment by imlikeTT** [comment]
hahaha but we're moving forward! this is how i declared the elements, nodes, and load:

%% DEFINING FEBIO INPUT STRUCTURE
 
[febio_spec]=febioStructTemplate;                           %Get a template with default settings 
febio_spec.ATTR.version='2.5';                            %febio_spec version
febio_spec.Module.ATTR.type='solid';                        %Module section
 
% CONTROL SECTION
febio_spec.Control.analysis.ATTR.type='static';
febio_spec.Control.time_steps=numTimeSteps;
febio_spec.Control.step_size=1/numTimeSteps;
febio_spec.Control.time_stepper.dtmin=dtmin;
febio_spec.Control.time_stepper.dtmax=dtmax;
febio_spec.Control.time_stepper.max_retries=max_retries;
febio_spec.Control.time_stepper.opt_iter=opt_iter;
febio_spec.Control.max_refs=max_refs;
febio_spec.Control.max_ups=max_ups;

% MATERIAL SECTION
febio_spec.Material.material{1}.ATTR.name='fibrotic';       %Name of the element set
febio_spec.Material.material{1}.ATTR.type='neo-Hookean';    %Adventicia
febio_spec.Material.material{1}.ATTR.id=1;
febio_spec.Material.material{1}.E=E1;
febio_spec.Material.material{1}.v=v1;

febio_spec.Material.material{2}.ATTR.name='tunica media';   %Name of the element set
febio_spec.Material.material{2}.ATTR.type='neo-Hookean';    %Media
febio_spec.Material.material{2}.ATTR.id=2;
febio_spec.Material.material{2}.E=E2;
febio_spec.Material.material{2}.v=v2;

febio_spec.Material.material{3}.ATTR.name='fibrofatty';     %Name of the element set
febio_spec.Material.material{3}.ATTR.type='neo-Hookean';    %Cellular Fibrosis
febio_spec.Material.material{3}.ATTR.id=3;
febio_spec.Material.material{3}.E=E3;
febio_spec.Material.material{3}.v=v3;

febio_spec.Material.material{4}.ATTR.name='necrotic core';  %Name of the element set
febio_spec.Material.material{4}.ATTR.type='neo-Hookean';    %Dense Fibrosis
febio_spec.Material.material{4}.ATTR.id=4;
febio_spec.Material.material{4}.E=E4;
febio_spec.Material.material{4}.v=v4;

febio_spec.Material.material{5}.ATTR.name='dense calcium'; %Name of the element set
febio_spec.Material.material{5}.ATTR.type='neo-Hookean';
febio_spec.Material.material{5}.ATTR.id=5;
febio_spec.Material.material{5}.E=E5;
febio_spec.Material.material{5}.v=v5;

%Geometry section
% -> Nodes
febio_spec.Geometry.Nodes{1}.ATTR.name='nodeSet_all'; %The node set name
febio_spec.Geometry.Nodes{1}.node.ATTR.id=(1:size(V,1))'; %The node id's
febio_spec.Geometry.Nodes{1}.node.VAL=V; %The nodel coordinates
 
% -> Elements
febio_spec.Geometry.Elements{1}.ATTR.type='tet4'; %Element type of this set
febio_spec.Geometry.Elements{1}.ATTR.mat=1; %material index for this set
febio_spec.Geometry.Elements{1}.ATTR.name='fibrotic'; %Name of the element set
febio_spec.Geometry.Elements{1}.elem.ATTR.id=(1:1:size(EP1,1))'; %Element id's
febio_spec.Geometry.Elements{1}.elem.VAL=EP1;
 
febio_spec.Geometry.Elements{2}.ATTR.type='tet4'; %Element type of this set
febio_spec.Geometry.Elements{2}.ATTR.mat=2; %material index for this set
febio_spec.Geometry.Elements{2}.ATTR.name='tunica media'; %Name of the element set
febio_spec.Geometry.Elements{2}.elem.ATTR.id=(1:1:size(EP2,1))'; %Element id's
febio_spec.Geometry.Elements{2}.elem.VAL=EP2;

febio_spec.Geometry.Elements{3}.ATTR.type='tet4'; %Element type of this set
febio_spec.Geometry.Elements{3}.ATTR.mat=3; %material index for this set
febio_spec.Geometry.Elements{3}.ATTR.name='fibrofatty'; %Name of the element set
febio_spec.Geometry.Elements{3}.elem.ATTR.id=(1:1:size(EP3,1))'; %Element id's
febio_spec.Geometry.Elements{3}.elem.VAL=EP3;

febio_spec.Geometry.Elements{4}.ATTR.type='tet4'; %Element type of this set
febio_spec.Geometry.Elements{4}.ATTR.mat=4; %material index for this set
febio_spec.Geometry.Elements{4}.ATTR.name='necrotic core'; %Name of the element set
febio_spec.Geometry.Elements{4}.elem.ATTR.id=(1:1:size(EP4,1))'; %Element id's
febio_spec.Geometry.Elements{4}.elem.VAL=EP4;
 
febio_spec.Geometry.Elements{5}.ATTR.type='tet4'; %Element type of this set
febio_spec.Geometry.Elements{5}.ATTR.mat=5; %material index for this set
febio_spec.Geometry.Elements{5}.ATTR.name='dense calcium'; %Name of the element set
febio_spec.Geometry.Elements{5}.elem.ATTR.id=(1:1:size(EP5,1))'; %Element id's
febio_spec.Geometry.Elements{5}.elem.VAL=EP5;


VwithNodes = [(1:length(V(:,1)))' V];
bcSupportNodesTemp = zeros(size(V(:,1)));

for tmp1 = 1:length(bcSupportList(:,1))
    distances = VwithNodes(:,[1 2 3 4]) - [0 bcSupportList(tmp1,:)];
    distancesMag = distances(:,[2 3 4]).*distances(:,[2 3 4]);
    distancesMagSum = (sum(distancesMag'))';
    [testing, index] = min(distancesMagSum);
    if testing < 0.1
        bcSupportNodesTemp(tmp1) = index;
    end
    tmp1;
end
bcSupportNodesTemp = unique(bcSupportNodesTemp);
bcSupportNodes = bcSupportNodesTemp(2:end);

% NODESETS
febio_spec.Geometry.NodeSet{1}.ATTR.name='bcSupportList';
febio_spec.Geometry.NodeSet{1}.node.ATTR.id=bcSupportNodes(:);

% SURFACES
febio_spec.Geometry.Surface{1}.ATTR.name='Pressure_surface';
febio_spec.Geometry.Surface{1}.tri3.ATTR.id=(1:size(F_pressure,1))';
febio_spec.Geometry.Surface{1}.tri3.VAL=F_pressure;

% BOUNDARY CONDITIONS
febio_spec.Boundary.fix{1}.ATTR.bc='x';
febio_spec.Boundary.fix{1}.ATTR.node_set=febio_spec.Geometry.NodeSet{1}.ATTR.name;
febio_spec.Boundary.fix{2}.ATTR.bc='y';
febio_spec.Boundary.fix{2}.ATTR.node_set=febio_spec.Geometry.NodeSet{1}.ATTR.name;
febio_spec.Boundary.fix{3}.ATTR.bc='z';
febio_spec.Boundary.fix{3}.ATTR.node_set=febio_spec.Geometry.NodeSet{1}.ATTR.name;

% BASELINE AORTIC LOADS
%   Systolic pressure  : 150 mmHg = 0.0199984 MPa
%   Diastolic pressure : 70  mmHg = 0.00933257 MPa
%   Mean pressure      : 105 mmHg = 0.0199984 MPa
%
% PATIENT 23 LOADS
%   Systolic pressure  : 138 mmHg = 0.0183985 MPa
%   Diastolic pressure : 64  mmHg = 0.00853263 MPa
%   Mean pressure      : 95  mmHg = 0.0126656 MPa

pressureValue=0.0126656;
febio_spec.Loads.surface_load{1}.ATTR.type='pressure';
febio_spec.Loads.surface_load{1}.ATTR.surface=febio_spec.Geometry.Surface{1}.ATTR.name;
febio_spec.Loads.surface_load{1}.pressure.VAL=pressureValue;
febio_spec.Loads.surface_load{1}.pressure.ATTR.lc=1;
 
% OUTPUT SECTION
% LOG FILE
febio_spec.Output.logfile.ATTR.file=febioLogFileName;
febio_spec.Output.logfile.node_data{1}.ATTR.file=febioLogFileName_disp;
febio_spec.Output.logfile.node_data{1}.ATTR.data='ux;uy;uz';
febio_spec.Output.logfile.node_data{1}.ATTR.delim=',';
febio_spec.Output.logfile.node_data{1}.VAL=1:size(V,1);
 
febio_spec.Output.logfile.node_data{2}.ATTR.file=febioLogFileName_force;
febio_spec.Output.logfile.node_data{2}.ATTR.data='Rx;Ry;Rz';
febio_spec.Output.logfile.node_data{2}.ATTR.delim=',';
febio_spec.Output.logfile.node_data{2}.VAL=1:size(V,1);

**Comment by Fireedman** [comment]
Ok

I verify your code and I haven´t find the error "the value for tag" tri3 "is invalid". The tag tri3 maybe it refers to a surface of triangulated elements, and the trouble could be that all of your different materials declared here is tet4. That means that the surface declared is quadrangulated. Maybe the error is that, verify in your previous code what kind of surface are using.
Verify this help file: https: //www.gibboncode.org/html/HELP_tri2quad.html or this one https://www.gibboncode.org/html/HELP_quad2tri.html to ensure that your mesh is declared correctly on this section.

Another recommendation is verify the demo 19 because it looks close similar to the procedure described in your code.
I assume this because, by reading your declared variables and how you are simulating a pressure, the proposed simulation is about an artery being inflated, but evaluating the impact of necrotic parts (heart attack maybe?) Or calcified elements (maybe an excess of fatty-tissues?) modify the pressure on the walls of the tissue (stiffening of the walls increase the stress pattern of the walls and that cause an increased propability of tear the tissue) ?. I suggest that you need to include contact behavior between all the elements of the artery to evaluate that possibility like demo 19 of documentation

**Comment by imlikeTT** [comment]
My list of tri3 does refer to a surface of triangulated faces. so are you saying the faces must be the same tag as the element it is associated with? I tried deleting the faces that were giving the issue from the XML and it seems to be working now. So I tried to put it through FEBio studio and it has no problem with any of the surfaces where pressure is applied to.. Im guessing my code is somehow breaking some of the faces? or perhaps the way I'm importing the Artery STL and pressure surface STL may also be causing this issue

Yes! i am following the demo 19 quite closely, since it is quite similar to the simulation i am running. You have a good eye haha 
As for the contact behavior, I don't see any defined in the demo 19, could you specify what you mean by that? Are you referring to a surface to surface / part to part contact? or perhaps element to element contact based on what material it is?

**Comment by Kevin-Mattheus-Moerman** [comment]
@imlikeTT if you are still encountering issues could you post a functional code that replicates the error?

**Comment by imlikeTT** [comment]
@Kevin-Mattheus-Moerman  Hi Dr. Moerman, if you could provide me your email I can send you an email? Perhaps we could schedule a call if you are available as well

**Comment by Kevin-Mattheus-Moerman** [comment]
@imlikeTT :point_right:  kevin.moerman@nuigalway.ie

**Comment by imlikeTT** [comment]
@Kevin-Mattheus-Moerman  Hi D.r Moerman, I cannot seem to reach you on that email. Does kmoerman@mit.edu work for you?

**Comment by Kevin-Mattheus-Moerman** [comment]
Both email addresses should work. Please resend an email and I'll get back to you.

**Comment by imlikeTT** [comment]
Thank you Dr. Moerman, I sent out the email out to your mit.edu email.
