### ISSUE TITLE
missing bulk modulus 'k'  in drop-down menu for Mooney-Rivlin as mixed solid

### ISSUE THREAD

**Issue by agsawa** [gibbonCode/GIBBON#80]
The option to assign 'k' (bulk modulus) after 'c1' and 'c2' for a Mooney-Rivlin material is available in the drop-down menu when using a single solid, but when including a coupled Mooney-Rivlin in a mixed-solid, only 'c1' and 'c2' are listed for assignment (no 'k').

**Comment by Kevin-Mattheus-Moerman** [comment]
@agsawa can you point to a demo or code that contains an issue. Is this an FEBioStudio issue of a GIBBON issue? If it is the former please go to: https://github.com/febiosoftware

**Comment by Kevin-Mattheus-Moerman** [comment]
@agsawa :point_up: let me know if you still need help with this. Pointing me in the right direction would help. Thanks.

**Comment by Kevin-Mattheus-Moerman** [comment]
I will close this issue for now as it appears to be stale and relating to FEBio rather than GIBBON.
