### ISSUE TITLE
troubles running DEMO 30

### ISSUE THREAD

**Issue by Fireedman** [gibbonCode/GIBBON#83]
Hi doctor, i´m studying DEMO 30 but when i run the code for FEBio 3.0 I get the next error

Error
tag "scale" (line 1667): invalid attribute "type"

I revised the code and when I comment the next line in MATLAB the code runs smoothly

febio_spec.Loads.nodal_load{1}.scale.ATTR.type='map';

But the results are not even closer to the reported in your documentation page. Thank you in advance

**Comment by Kevin-Mattheus-Moerman** [comment]
@Fireedman thanks for posting this, apologies for the delay in getting back to you. 

Can you confirm if this is still an issue with the latest FEBio version (e.g. version 3 that ships with the latest FEBioStudio) and the latest GIBBON version? 

FEBio has made a lot of changes recently so there are a lot of new bugs/issues I've been working on fixing. It is best though at this point to switch to FEBio3. Quite a lot of demos have transitioned to it already. 

I'll close this issue for now, but do let me know if you need more help and I'll reopen this issue.
