### ISSUE TITLE
Selecting interfaces for friction contact

### ISSUE THREAD

**Issue by YChang20** [gibbonCode/GIBBON#84]
Hi,

I am modeling the mechanical responses of a fibrous composite.
I successfully created the model, and I want to apply friction on the fibre/matrix interfaces (as the shaded yellow region in the attached figure).
Inspired by DEMO_febio_0029_contact_friction_benchmark_boxes, I think it is possible to do it.
However, I get stuck in selecting the interfaces. I was wondering if someone can give suggestions on selecting the interfaces, so I can assign the contact friction?

Any suggestion is welcome. Thank you.

Best,
Yin
![frictionmode](https://user-images.githubusercontent.com/22903956/104659749-2127db80-56bd-11eb-90da-646f084f7c6f.jpg)
[frictionfiber.txt](https://github.com/gibbonCode/GIBBON/files/5817442/frictionfiber.txt)

**Comment by Kevin-Mattheus-Moerman** [comment]
Hi @YChang20 thanks for posting this and apologies for the delay in getting back to you. From that picture it looks like you meshed the whole thing with TetGen using GIBBON. You likely had face labels for each of those regions. It sounds like (unless I am wrong) that the next step should be to get the material regions and separate them again (they are currently sharing nodes across interfaces). After separation you can create the separate boundary face lists that can serve for your contact faces. 
The separation and list search is a bit cryptic. I'd be happy to chat with you if you are still struggling. Shoot me an email if interested in chatting: kevin.moerman@nuigalway.ie

**Comment by Kevin-Mattheus-Moerman** [comment]
Closing this as stale
