### ISSUE TITLE
tetg

### ISSUE THREAD

**Issue by Ezail88** [gibbonCode/GIBBON#87]
i'm trying hard to tetrahelize using tetg in freefem++.  Hereby the problem : a cubic box with perforated rectangle on all 4 faces of the cube, meaning, a face is perforated by rectangle hole. I'm finding difficult to tetrahelize it. 
Hereby my code in freefem++ :
`load "msh3"
load "TetGen"
load "medit"

// DECLARATION OF LOCAL VARIABLES
int nelx = 100;
real theta,thetamoy,rho;
// rescale coefficents
real c1,c2;
// cell's parameter
real m1,m2;
real mx,my; //bar's width
real Inelx,Inely;
int iter = 0;
int samplesize = 1000;
real epsil = .005;
real stepsize1 = 1./samplesize;
real stepsize2 = stepsize1*.5;
//STATIC VARIABLES
real sqrt3 = sqrt(3.);
real sqrt2 = sqrt(2.);
real pi=4*atan(1); // pi=3.14159...

/////////////////////////
//Boundary definitions //
/////////////////////////
// square region
border sb1(t=0,1){x=t; y=0;label=1;};
border sb2(t=0,1){x=1;y=t;label=2;};
border sb3(t=0,1){x=1-t;y=1;label=3;};
border sb4(t=0,1){x=0;y=1-t;label=4;};
// the inscribed rectangle
border insb1(t=0,1){x=mx+(1-2*mx)*t;y=my;label=11;};
border insb2(t=0,1){x=1-mx;y=my+(1-2*my)*t;label=22;};
border insb3(t=0,1){x=1-mx+(2*mx-1)*t;y=1-my;label=33;};
border insb4(t=0,1){x=mx;y=1-my+(2*my-1)*t;label=44;};

iter = 100;
//for(iter=0;iter<samplesize;iter++){
m1 = 1-epsil -(1-2*epsil)*iter*stepsize1;
m2 = 1-epsil -(1-2*epsil)*iter*stepsize2;
mx = (1-m1)/2;
my = (1-m2)/2;
theta = 1-m1*m2;
Inelx = int(nelx*m1);
Inely = int(nelx*m2);

/////////////////////
// Mesh definition //
/////////////////////

mesh Th=buildmesh(sb1(nelx)+sb2(nelx)+sb3(nelx)+sb4(nelx));
real volume = int2d(Th)(1.);
mesh Th1,Th2,Th3;
Th1 = buildmesh(sb1(nelx)+sb2(nelx)+sb3(nelx)+sb4(nelx)
+insb1(-Inelx)+insb2(-Inely)+insb3(-Inelx)+insb4(-Inely));
Th2 = Th1;
Th3 = Th1;

int[int] r1=[1,11,2,12,3,13,4,14];
int[int] r2=[1,21,2,22,3,23,4,24];
int[int] r3=[1,31,2,32,3,33,4,34];
Th1 = change(Th1, label=r1);
Th2 = change(Th2, label=r2);
Th3 = change(Th3, label=r3);  
// Parameters
func ZZ1min = 0.;//down :5
func ZZ1max = 1.;//top  :6
func XX1 = x;
func YY1 = y;

func ZZ2 = y;
func XX2 = x;
func YY2min = 0.;//front :1
func YY2max = 1.;//back  :3

func ZZ3 = x;
func YY3 = y;
func XX3min = 0.;//left  :4
func XX3max = 1.;//right :2

// Mesh 2D to 3D surface
meshS Th31h = movemesh23(Th1, transfo=[XX1, YY1, ZZ1max], orientation=1);
meshS Th31b = movemesh23(Th1, transfo=[XX1, YY1, ZZ1min], orientation=-1);

meshS Th32h = movemesh23(Th2, transfo=[XX2, YY2max, ZZ2], orientation=-1);
meshS Th32b = movemesh23(Th2, transfo=[XX2, YY2min, ZZ2], orientation=1);

meshS Th33h = movemesh23(Th3, transfo=[XX3max, YY3, ZZ3], orientation=-1);
meshS Th33b = movemesh23(Th3, transfo=[XX3min, YY3, ZZ3], orientation=1);

 
//int[int] re=[1,1, 2,1, 3,1, 4,1] //3d

// Gluing surfaces
meshS Th33 = Th31h + Th31b + Th32h + Th32b + Th33h + Th33b;
plot(Th33, cmm="Th33");

// Tetrahelize the interior of the cube with TetGen
real[int] holes = [0.5,0.,0.5,1.,0.5,0.5,0.5,1.,0.5,0.,0.5,0.5,0.5,0.5,0.,0.5,0.5,1.];
real[int] domain=[x, y, z,0, 0.0025];
mesh3 Thfinal = tetg(Th33, switch="paAAQY", regionlist=domain,nbofholes=6,holelist=holes);
plot(Thfinal, cmm="Thfinal");

//};`

**Comment by Kevin-Mattheus-Moerman** [comment]
@Ezail88 this looks like a freefem++ issue (so perhaps you posted this on the wrong repository). I'll close this for now but let me know if you want help in using GIBBON and MATLAB for meshing with TetGen.
