### ISSUE TITLE
FEbio Foot insole demo

### ISSUE THREAD

**Issue by g-racer** [gibbonCode/GIBBON#88]
I am trying to run the insole demo with FEbio. I am new to the software but familiar with MATLB and have tried to update the code to match the latest version of FEbio however I am still getting the error " * Model initialization failed                                           * . Any help would be appreciated! I have attached my matlab code and model as txt files

[insolemodel.txt](https://github.com/gibbonCode/GIBBON/files/6186273/insolemodel.txt)

[DEMO_febio_0050_foot_insole_01.txt](https://github.com/gibbonCode/GIBBON/files/6186262/DEMO_febio_0050_foot_insole_01.txt)

**Comment by Kevin-Mattheus-Moerman** [comment]
@g-racer thanks for posting this issue and apologies for getting to it late. Are you still stuck with this? 

What is your operational system? (e.g. Linux, Mac, or Windows?)
What FEBio version are you using? 
Are you using the latest GIBBON version? 
Can you create a screenshot of any errors in MATLAB?

**Comment by Kevin-Mattheus-Moerman** [comment]
@g-racer I have now updated that demo and it should run with the latest versions of FEBio and GIBBON. Let me know if you are still stuck.

**Comment by Kevin-Mattheus-Moerman** [comment]
@g-racer I'll close this for now but let me know if you still need help.
