### ISSUE TITLE
Why Invalid file identifier issue is happening in WINDOWS 10 Pro

### ISSUE THREAD

**Issue by sroyiitd** [gibbonCode/GIBBON#89]
I am getting this error while running any demo file from my working directory, which is outside Program Files forlder. 

Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in cell2txtfile (line 63)
        fprintf(fid,'%s\r\n', T{:});

Error in febioStruct2xml>textModeElementAttributeParse (line 351)
cell2txtfile(fileName,totalTextCell,0,0); %Export to text file

and more.......

COULD you please tell why this is happening?

**Comment by Kevin-Mattheus-Moerman** [comment]
@sroyiitd thanks for posting this. I need some more information. Can you tell me what demo you are running? Can you update to the latest FEBio and GIBBON version and test this again? 

Where do you have the GIBBON folder on your system? If you have placed in a folder where you do not have read/write permissions via MATLAB then this could be the issue. For instance some windows users place the GIBBON folder in the C->program files -> MATLAB folder which is not a location where one would have these permissions. 

Can you make sure you place GIBBON in a location where you have full permissions? E.g. your down Documents folder would do for instance. 

Let me know how you get on.

**Comment by sroyiitd** [comment]
Kevin, yes it ran....Thanks a bunch....I am feeling embarrassed, I should have guessed a 3rd party toolbox need to be placed outside the C->Programfiles\MATLAB\ToolBox .....earlier I kept in the toolbox, and I was changing my working directory in MATLAB it ran up to the pre-processor portion, but gave a problem when I needed to generate the XML file. 

Thanks a bunch, it solved my problem

**Comment by sroyiitd** [comment]
BTW, I am using a FEBio version 3.3.3 
May I know what is the latest version of GIBBON released till date?

**Comment by Kevin-Mattheus-Moerman** [comment]
Great that it works @sroyiitd. I'll close this issue now but let me know if you need anything else and I can reopen it. 

By latest GIBBON I meant the latest code available here on GitHub.
