### ISSUE TITLE
Tetgen (called from Gibbon) can mesh the tube but results in missing some elements in defining the no slip wall

### ISSUE THREAD

**Issue by alibehrang** [gibbonCode/GIBBON#94]
Hi,
I am working on generating a bifurcated tube (from scratch) using Gibbon/Matlab and performing FEA and CFD and eventually FSI on it. I have completed the FEA part (mesh and analysis) and I am having trouble with the CFD mesh that is generated by Tetgen from Gibbon. The mesh looks ok, but I cannot define wall elements for no-slip boundary condition. The problem is that Tetgen generates some elements on the inner surface with all 4 nodes (1st order tetrahedral) being on the surface. In other words, I have two faces of an element on the wall and thus I am missing some elements when I am defining (list of elements) this wall no matter how I re-orient those elements. Do you know how I can prevent this? Image 1 is showing some of the missing elements and image 2 shows that those elements have two faces on the surface.
![Gibbon_2](https://user-images.githubusercontent.com/62657624/117715731-aff9c000-b1a6-11eb-94b7-2d15145323b1.JPG)
![Gibbon_1](https://user-images.githubusercontent.com/62657624/117715768-ba1bbe80-b1a6-11eb-9829-06c27dd9b180.JPG)

**Comment by Kevin-Mattheus-Moerman** [comment]
Apologies I did not get to your issue in a timely manor. 

I do believe the TetGen interface can use improvements. It is on my list of things to do in the future. 

I'll assume this issue is now too old. I'll therefore close it for now, but do let me know if you still have problems.
