### ISSUE TITLE
Consider using a cloud CI service

### ISSUE THREAD

**Issue by acampbel** [gibbonCode/GIBBON#95]
Given public open source projects have free support for cloud ci services, consider leveraging one of them here. 🎉

https://blogs.mathworks.com/developer/2020/12/15/cloud-ci-services/

**Comment by Kevin-Mattheus-Moerman** [comment]
@acampbel if you are able to advise on this let me know or create a pull request to help make this happen. I'll close this for now but let me know if you want to discus this further.

**Comment by acampbel** [comment]
Hi @Kevin-Mattheus-Moerman, thanks for considering! We have an [example repo](https://github.com/mathworks/ci-configuration-examples) that shows how you can get started very easily one one of the supported platforms. GitHub Actions might be pretty easy to get started because they work natively with GitHub and you dont need to sign up for another service or enable a GitHub App or anything. However, your toolbox seems fairly graphics focused, and at least currently GitHub Actions runs headless. If that is an issue with your repo then you might consider one of the other platforms, like CircleCI.

As for what to code to execute in this CI build int seems like contributors to your repo with more domain knowledge would be needed. You certainly can consider utilizing the [test frameworks](https://www.mathworks.com/help/matlab/matlab-unit-test-framework.html) to build up a solid test bed for this codebase. However, even without that, it looks like you can run the [`testGibbon`](https://github.com/gibbonCode/GIBBON/blob/master/lib/testGibbon.m) command using something like [`matlab-actions/run-command`](https://github.com/matlab-actions/run-command) or [`matlab/run-command`](https://circleci.com/developer/orbs/orb/mathworks/matlab#commands-run-command). 

Does that help?

**Comment by acampbel** [comment]
@Kevin-Mattheus-Moerman bump on the thread....also happy to join a call to help if you are interested but need support to get going
