### ISSUE TITLE
Install GIBBON in an environment without root access

### ISSUE THREAD

**Issue by mbarzegary** [gibbonCode/GIBBON#98]
Hi Kevin,

As I told you in the VPH hands-on session, it's impossible to install GIBBON in a Windows environment without the admin privilege (I'm not sure about Linux, but it should be the same). There are two reasons behind this: 

1. FEBio needs a root access to be installed (I can't understand why they need an installation file since the installer does nothing but extracting and copying files, and the user can simply move the installed files to another system, meaning that the program is actually a portable one, so they can also release it as a portable version for this scenario. but, anyway, this is irrelevant to GIBBON). 

2. Setting the path inside MATLAB (the operation that the installer script tries to do) requires the root access in most of the Windows installation cases (because it gets installed in Program Files). Thus, it becomes impossible to use the installation GUI to install GIBBON. 

The workaround is quite simple but is not trivial. It can be nice if you extend the installation documentation to explain how to manually modify the path when the user doesn't have a root access.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mbarzegary thanks for raising this. 

I'm copying in @SteveMaas1978 from the FEBio team about the first point. 

I can work on adding manual GIBBON installation (unzipping data, adding folders to the path etc.) which would avoid this issue. If you have found a way to do it and want to help add instructions on this that would be great. I'd welcome a pull request to address this. 

FYI one can also add GIBBON paths to the MATLAB path at runtime using 
```matlab
addpath(libPath);
```
where `libPath` could be the `/lib` folder or any other required GIBBON folder.

**Comment by Kevin-Mattheus-Moerman** [comment]
@mbarzegary is this still an issue? Let me know if you need more help or if I can close this now.
