### ISSUE TITLE
Error writing to XML - FEBio

### ISSUE THREAD

**Issue by jszyszko** [gibbonCode/GIBBON#99]
Hello Everyone,
I am trying to run one of the DEMO simulation (https://www.gibboncode.org/html/DEMO_febio_0011_cube_multi_generation.html)  through GIBBON to FEBio but I have some errors while writing it to the XML file format. I would appreciate any help :)
These are the following errors:
Undefined function or variable 'attributeStruct'.

Error in febioStruct2xml>febioStruct2xmlStep (line 178)
                            [domNode,rootNode]=textModeElementAttributeParse(domNode,rootNode,currentFieldName,attributeStruct,arrayDataSet,numArray,fieldNameSetSub,fileName,arrayParseMethod);
                            
Error in febioStruct2xml>recursiveElementParse (line 223)
    [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,currentFieldValue,optionStruct,fileName); %Add whatever is nested in
    here

Error in febioStruct2xml>febioStruct2xmlStep (line 210)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml>recursiveElementParse (line 228)
        [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,parseStructSub,optionStruct,fileName); %Add whatever is nested in
        here

Error in febioStruct2xml>febioStruct2xmlStep (line 210)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml>recursiveElementParse (line 223)
    [domNode,elementNode]=febioStruct2xmlStep(domNode,elementNode,currentFieldValue,optionStruct,fileName); %Add whatever is nested in
    here

Error in febioStruct2xml>febioStruct2xmlStep (line 210)
                [domNode,rootNode]=recursiveElementParse(domNode,rootNode,currentFieldName,currentFieldValue,optionStruct,fileName);

Error in febioStruct2xml (line 78)
[domNode]=febioStruct2xmlStep(domNode,rootNode,parseStruct,optionStruct,fileName);

Error in cubetrial (line 217)
febioStruct2xml(febio_spec,febioFebFileName); %Exporting to file and domNode

**Comment by Kevin-Mattheus-Moerman** [comment]
@jszyszko thanks for posting this and taking the time to try out GIBBON. 

That demo, `DEMO_febio_0014_cube_varying_material` should work with the latest FEBio version and latest GIBBON version. 

Note this uses `febio_spec` 3.0 which requires the latest FEBio. 

Can you let me know if the problem persists with the latest versions? What version are you using? What is your operational system? 

Thanks.

**Comment by jszyszko** [comment]
@Kevin-Mattheus-Moerman thank you or answering. Actually I was using the febio 3.3 version - now I'm running it ios using the 3.0 version and it's working. Thank you for the information :).

**Comment by Kevin-Mattheus-Moerman** [comment]
@jszyszko great. I'll close this now as it seems resolved. Let me know if you have any other questions/issues. 

If you create anything useful that you'd like to share and include in GIBBON please consider a pull-request. I always welcome contributions.
